-- EduNova Portal Extension #4 — Complete Admission Workflow Tables
-- Run this AFTER portal_extension_auth_user.sql and portal_extension_parent_admin.sql
-- Safe to run multiple times: every statement is IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.

-- ---------------------------------------------------------------------------
-- Phase 1: Admission Enquiry tracking (extends admissions_admissionenquiry)
-- ---------------------------------------------------------------------------
ALTER TABLE public.admissions_admissionenquiry ADD COLUMN IF NOT EXISTS source_of_enquiry varchar(50) DEFAULT 'Website';
ALTER TABLE public.admissions_admissionenquiry ADD COLUMN IF NOT EXISTS preferred_branch varchar(150) DEFAULT '';
ALTER TABLE public.admissions_admissionenquiry ADD COLUMN IF NOT EXISTS curriculum varchar(30) DEFAULT 'CBSE';
ALTER TABLE public.admissions_admissionenquiry ADD COLUMN IF NOT EXISTS counsellor_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL;
ALTER TABLE public.admissions_admissionenquiry ADD COLUMN IF NOT EXISTS counselling_status varchar(30) DEFAULT 'Pending';
ALTER TABLE public.admissions_admissionenquiry ADD COLUMN IF NOT EXISTS counselling_notes text DEFAULT '';
ALTER TABLE public.admissions_admissionenquiry ADD COLUMN IF NOT EXISTS counselling_date timestamptz;

-- ---------------------------------------------------------------------------
-- Phase 4: Extended student details (application form data)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_application (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id integer NOT NULL REFERENCES public.admissions_admissionenquiry(id) ON DELETE CASCADE,
  
  -- Student Details
  blood_group varchar(10) DEFAULT '',
  aadhaar_number varchar(20) DEFAULT '',
  nationality varchar(50) DEFAULT 'Indian',
  religion varchar(50) DEFAULT '',
  category varchar(30) DEFAULT 'General',
  student_photo_url text DEFAULT '',
  
  -- Father Details
  father_name varchar(150) DEFAULT '',
  father_occupation varchar(100) DEFAULT '',
  father_company varchar(150) DEFAULT '',
  father_income numeric DEFAULT 0,
  father_phone varchar(20) DEFAULT '',
  father_email varchar(150) DEFAULT '',
  
  -- Mother Details
  mother_name varchar(150) DEFAULT '',
  mother_occupation varchar(100) DEFAULT '',
  mother_company varchar(150) DEFAULT '',
  mother_phone varchar(20) DEFAULT '',
  mother_email varchar(150) DEFAULT '',
  
  -- Guardian Details
  guardian_name varchar(150) DEFAULT '',
  guardian_relationship varchar(50) DEFAULT '',
  guardian_phone varchar(20) DEFAULT '',
  guardian_address text DEFAULT '',
  
  -- Address Details
  permanent_address text DEFAULT '',
  communication_address text DEFAULT '',
  pin_code varchar(10) DEFAULT '',
  state varchar(100) DEFAULT '',
  district varchar(100) DEFAULT '',
  
  -- Academic Details
  previous_school varchar(200) DEFAULT '',
  board varchar(50) DEFAULT '',
  previous_class varchar(50) DEFAULT '',
  percentage numeric DEFAULT 0,
  transfer_certificate_url text DEFAULT '',
  reason_for_leaving text DEFAULT '',
  
  -- Medical Information
  allergies text DEFAULT '',
  medical_conditions text DEFAULT '',
  emergency_contact_name varchar(150) DEFAULT '',
  emergency_contact_phone varchar(20) DEFAULT '',
  emergency_contact_relation varchar(50) DEFAULT '',
  
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (enquiry_id)
);

-- ---------------------------------------------------------------------------
-- Phase 5: Document Upload tracking
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_document (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id integer NOT NULL REFERENCES public.admissions_admissionenquiry(id) ON DELETE CASCADE,
  document_type varchar(50) NOT NULL,
  document_name varchar(200) NOT NULL,
  file_url text NOT NULL,
  file_size integer DEFAULT 0,
  file_type varchar(20) DEFAULT '',
  is_verified boolean DEFAULT false,
  verified_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  verification_notes text DEFAULT '',
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  verified_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_admission_doc_enquiry ON public.portal_admission_document(enquiry_id);

-- ---------------------------------------------------------------------------
-- Phase 6: Eligibility Validation results
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_eligibility (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id integer NOT NULL REFERENCES public.admissions_admissionenquiry(id) ON DELETE CASCADE,
  age_eligible boolean DEFAULT false,
  academic_eligible boolean DEFAULT false,
  documents_eligible boolean DEFAULT false,
  overall_eligible boolean DEFAULT false,
  age_reason text DEFAULT '',
  academic_reason text DEFAULT '',
  document_reason text DEFAULT '',
  validated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (enquiry_id)
);

-- ---------------------------------------------------------------------------
-- Phase 8: Interview / Assessment
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_interview (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id integer NOT NULL REFERENCES public.admissions_admissionenquiry(id) ON DELETE CASCADE,
  interviewer_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  interview_date timestamptz,
  interview_type varchar(30) DEFAULT 'Interview',
  status varchar(30) DEFAULT 'Scheduled',
  marks_obtained numeric DEFAULT 0,
  max_marks numeric DEFAULT 100,
  recommendation varchar(30) DEFAULT '',
  remarks text DEFAULT '',
  parent_notified boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admission_interview_enquiry ON public.portal_admission_interview(enquiry_id);

-- ---------------------------------------------------------------------------
-- Phase 9: Seat Allocation
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_seat (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id integer NOT NULL REFERENCES public.admissions_admissionenquiry(id) ON DELETE CASCADE,
  class_id integer REFERENCES public.portal_class(id) ON DELETE SET NULL,
  section varchar(10) DEFAULT '',
  campus_id integer,
  is_waitlisted boolean DEFAULT false,
  waitlist_position integer,
  seat_reserved_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (enquiry_id)
);

-- ---------------------------------------------------------------------------
-- Phase 11: Fee Payment tracking for admissions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_fee (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id integer NOT NULL REFERENCES public.admissions_admissionenquiry(id) ON DELETE CASCADE,
  fee_type varchar(50) DEFAULT 'Admission_Fee',
  total_amount numeric NOT NULL DEFAULT 0,
  scholarship_discount numeric DEFAULT 0,
  net_amount numeric NOT NULL DEFAULT 0,
  is_paid boolean DEFAULT false,
  transaction_id varchar(100) DEFAULT '',
  payment_method varchar(40) DEFAULT '',
  payment_date timestamptz,
  invoice_number varchar(50) DEFAULT '',
  receipt_url text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (enquiry_id)
);

-- ---------------------------------------------------------------------------
-- Phase 14: Academic Allocation for new admissions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id integer NOT NULL REFERENCES public.admissions_admissionenquiry(id) ON DELETE CASCADE,
  student_user_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  class_id integer REFERENCES public.portal_class(id) ON DELETE SET NULL,
  section varchar(10) DEFAULT '',
  house varchar(30) DEFAULT '',
  class_teacher_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  roll_number integer,
  academic_year varchar(20) DEFAULT '',
  allocated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (enquiry_id)
);

-- ---------------------------------------------------------------------------
-- Phase 15: Optional Module Allocation (Transport/Hostel/Library/LMS)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_module_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id integer NOT NULL REFERENCES public.admissions_admissionenquiry(id) ON DELETE CASCADE,
  module_type varchar(30) NOT NULL,
  allocation_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  allocated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admission_module_enquiry ON public.portal_admission_module_allocation(enquiry_id);

-- ---------------------------------------------------------------------------
-- Phase 16: Notification tracking for admission workflow
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_notification (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id integer REFERENCES public.admissions_admissionenquiry(id) ON DELETE CASCADE,
  recipient_type varchar(30) NOT NULL,
  recipient_user_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  notification_type varchar(50) NOT NULL,
  title varchar(200) NOT NULL,
  message text NOT NULL,
  channel varchar(20) DEFAULT 'in_app',
  is_sent boolean DEFAULT false,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admission_notif_enquiry ON public.portal_admission_notification(enquiry_id);
CREATE INDEX IF NOT EXISTS idx_admission_notif_recipient ON public.portal_admission_notification(recipient_user_id);

-- ---------------------------------------------------------------------------
-- Phase 18: Reports & Analytics snapshot
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_admission_analytics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_date date NOT NULL DEFAULT current_date,
  total_enquiries integer DEFAULT 0,
  new_enquiries integer DEFAULT 0,
  converted integer DEFAULT 0,
  rejected integer DEFAULT 0,
  waitlisted integer DEFAULT 0,
  pending integer DEFAULT 0,
  fee_collected numeric DEFAULT 0,
  branch_wise jsonb DEFAULT '{}'::jsonb,
  class_wise jsonb DEFAULT '{}'::jsonb,
  gender_wise jsonb DEFAULT '{}'::jsonb,
  source_wise jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
