# Generated by Django 5.0.6 on 2026-07-17 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examinationtype')),
            ],
        ),
        migrations.CreateModel(
            name='MarkStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=50)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ('internal_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('external_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('practical_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_structures', to='examination.examination')),
            ],
        ),
    ]
