import json
from datetime import date, datetime, timedelta

from django.db import connection
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .admin_views import AdminMixin
from .roles import get_role, log_action
from .views import row, rows, serialise, table_exists


# ---------------------------------------------------------------------------
# Ensure portal_assignment_rubric table exists (idempotent DDL)
# ---------------------------------------------------------------------------
def _ensure_rubric_table():
    if table_exists("portal_assignment_rubric"):
        return True
    try:
        with connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS public.portal_assignment_rubric (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    assignment_id integer NOT NULL REFERENCES public.portal_assignment(id) ON DELETE CASCADE,
                    criterion text NOT NULL,
                    max_marks smallint NOT NULL DEFAULT 10,
                    description text DEFAULT '',
                    sort_order smallint DEFAULT 0,
                    created_at timestamptz NOT NULL DEFAULT now()
                );
                CREATE INDEX IF NOT EXISTS idx_rubric_assignment ON public.portal_assignment_rubric(assignment_id);
            """)
        return True
    except Exception:
        return False


# ---------------------------------------------------------------------------
# 1. Assignment Category Management
# ---------------------------------------------------------------------------
class AssignmentCategoryView(AdminMixin, APIView):
    """GET  — list assignment categories
    POST — create a new assignment category
    DELETE ?id= — remove a category"""

    CATEGORY_TABLE = "portal_assignment_category"

    def _ensure_table(self):
        try:
            with connection.cursor() as cursor:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS public.portal_assignment_category (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(50) NOT NULL UNIQUE,
                        description text DEFAULT '',
                        is_active boolean DEFAULT true,
                        created_at timestamptz NOT NULL DEFAULT now()
                    );
                """)
                # Seed defaults if empty
                cursor.execute("SELECT COUNT(*)::int FROM portal_assignment_category")
                if cursor.fetchone()[0] == 0:
                    categories = [
                        ('Homework', 'Regular homework assignments'),
                        ('Worksheet', 'Practice worksheets'),
                        ('Project', 'Long-term project work'),
                        ('Research', 'Research-based assignments'),
                        ('Practical_Record', 'Lab practical records'),
                        ('Lab_Report', 'Laboratory experiment reports'),
                        ('Presentation', 'Oral or slide presentations'),
                        ('Essay', 'Written essays'),
                        ('Coding', 'Programming and coding tasks'),
                        ('Case_Study', 'Case study analysis'),
                        ('Group', 'Group-based assignments'),
                    ]
                    for name, desc in categories:
                        cursor.execute(
                            "INSERT INTO portal_assignment_category (name, description) VALUES (%s,%s) ON CONFLICT DO NOTHING",
                            [name, desc],
                        )
        except Exception:
            pass

    def get(self, request):
        self._ensure_table()
        if not table_exists(self.CATEGORY_TABLE):
            return Response([])
        sql = "SELECT * FROM portal_assignment_category"
        params = []
        active_only = request.query_params.get("active")
        if active_only is not None and active_only.lower() in ("1", "true", "yes"):
            sql += " WHERE is_active = true"
        sql += " ORDER BY id"
        return Response(serialise(rows(sql, params)))

    def post(self, request):
        self._ensure_table()
        if not table_exists(self.CATEGORY_TABLE):
            return Response({"detail": "Category table not found."}, status=400)
        d = request.data
        name = (d.get("name") or "").strip()
        if not name:
            return Response({"detail": "name is required."}, status=400)
        description = d.get("description", "")
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_assignment_category (name, description, is_active) VALUES (%s,%s,%s) RETURNING id",
                [name, description, d.get("is_active", True)],
            )
            new_id = cursor.fetchone()[0]
        log_action(request.user, "assignment_category.create", self.CATEGORY_TABLE, new_id, {"name": name})
        return Response({"id": new_id, "detail": "Category created."}, status=201)

    def delete(self, request):
        self._ensure_table()
        if not table_exists(self.CATEGORY_TABLE):
            return Response({"detail": "Table not found."}, status=400)
        rec_id = request.query_params.get("id")
        if not rec_id:
            return Response({"detail": "id is required."}, status=400)
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM portal_assignment_category WHERE id=%s RETURNING id", [rec_id])
            deleted = cursor.fetchone()
        if not deleted:
            return Response({"detail": "Not found."}, status=404)
        log_action(request.user, "assignment_category.delete", self.CATEGORY_TABLE, rec_id, {})
        return Response({"detail": "Deleted."})


# ---------------------------------------------------------------------------
# 2. Assignment Scheduling (Admin + Teacher)
# ---------------------------------------------------------------------------
class AssignmentSchedulingView(APIView):
    """Full CRUD for assignments. Admin can manage all; Teacher can manage their own.
    GET    ?class_id=&subject_id=&teacher_id=&type= — list assignments
    POST   — create assignment
    PUT    — update assignment
    DELETE ?id= — delete assignment"""

    permission_classes = [IsAuthenticated]

    def _check_permission(self, request):
        role = get_role(request.user)
        if role not in ("Admin", "Teacher"):
            return False, role
        return True, role

    def get(self, request):
        if not table_exists("portal_assignment"):
            return Response([])
        d = request.query_params
        sql = """
            SELECT a.id, a.class_id, a.subject_id, a.teacher_id, a.title, a.description,
                   a.file_url, a.max_marks, a.due_date, a.assignment_type, a.quiz_questions,
                   s.name AS subject_name,
                   c.name || '-' || c.section AS class_name,
                   COALESCE(u.first_name || ' ' || u.last_name, u.username) AS teacher_name,
                   (SELECT COUNT(*)::int FROM portal_assignment_submission sub WHERE sub.assignment_id = a.id) AS submission_count
            FROM portal_assignment a
            LEFT JOIN portal_subject s ON s.id = a.subject_id
            LEFT JOIN portal_class c ON c.id = a.class_id
            LEFT JOIN auth_user u ON u.id = a.teacher_id
        """
        conditions = []
        params = []
        if d.get("class_id"):
            conditions.append("a.class_id = %s")
            params.append(d["class_id"])
        if d.get("subject_id"):
            conditions.append("a.subject_id = %s")
            params.append(d["subject_id"])
        if d.get("teacher_id"):
            conditions.append("a.teacher_id = %s")
            params.append(d["teacher_id"])
        if d.get("type"):
            conditions.append("a.assignment_type = %s")
            params.append(d["type"])
        if conditions:
            sql += " WHERE " + " AND ".join(conditions)
        sql += " ORDER BY a.due_date DESC NULLS LAST"
        return Response(serialise(rows(sql, params)))

    def post(self, request):
        ok, role = self._check_permission(request)
        if not ok:
            return Response({"detail": "Admin or Teacher role required."}, status=403)
        if not table_exists("portal_assignment"):
            return Response({"detail": "Assignment table not found."}, status=400)
        d = request.data
        title = (d.get("title") or "").strip()
        class_id = d.get("class_id")
        subject_id = d.get("subject_id")
        if not title or not class_id or not subject_id:
            return Response({"detail": "title, class_id, and subject_id are required."}, status=400)
        teacher_id = d.get("teacher_id") or request.user.id
        description = d.get("description", "")
        file_url = d.get("file_url", "")
        max_marks = d.get("max_marks", 100)
        due_date = d.get("due_date")
        assignment_type = d.get("assignment_type", "Assignment")
        quiz_questions = d.get("quiz_questions")
        if quiz_questions is not None and not isinstance(quiz_questions, str):
            quiz_questions = json.dumps(quiz_questions)

        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_assignment "
                "(class_id, subject_id, teacher_id, title, description, file_url, max_marks, due_date, assignment_type, quiz_questions) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                [class_id, subject_id, teacher_id, title, description, file_url,
                 max_marks, due_date, assignment_type, quiz_questions],
            )
            new_id = cursor.fetchone()[0]
        log_action(request.user, "assignment.create", "portal_assignment", new_id,
                   {"title": title, "class_id": class_id, "subject_id": subject_id})
        return Response({"id": new_id, "detail": "Assignment created."}, status=201)

    def put(self, request):
        ok, role = self._check_permission(request)
        if not ok:
            return Response({"detail": "Admin or Teacher role required."}, status=403)
        if not table_exists("portal_assignment"):
            return Response({"detail": "Table not found."}, status=400)
        d = request.data
        rec_id = d.get("id")
        if not rec_id:
            return Response({"detail": "id is required."}, status=400)
        existing = row("SELECT id FROM portal_assignment WHERE id=%s", [rec_id])
        if not existing:
            return Response({"detail": "Assignment not found."}, status=404)
        # Teachers can only edit their own
        if role == "Teacher":
            own = row("SELECT teacher_id FROM portal_assignment WHERE id=%s", [rec_id])
            if own and own["teacher_id"] != request.user.id:
                return Response({"detail": "You can only edit your own assignments."}, status=403)

        fields = []
        vals = []
        for col in ("title", "description", "file_url", "max_marks", "due_date", "class_id",
                     "subject_id", "teacher_id", "assignment_type"):
            if col in d:
                fields.append(f"{col} = %s")
                vals.append(d[col])
        if "quiz_questions" in d:
            qq = d["quiz_questions"]
            if qq is not None and not isinstance(qq, str):
                qq = json.dumps(qq)
            fields.append("quiz_questions = %s")
            vals.append(qq)
        if not fields:
            return Response({"detail": "No fields to update."}, status=400)
        vals.append(rec_id)
        with connection.cursor() as cursor:
            cursor.execute(f"UPDATE portal_assignment SET {', '.join(fields)} WHERE id = %s", vals)
        log_action(request.user, "assignment.update", "portal_assignment", rec_id, d)
        return Response({"detail": "Updated."})

    def delete(self, request):
        ok, role = self._check_permission(request)
        if not ok:
            return Response({"detail": "Admin or Teacher role required."}, status=403)
        if not table_exists("portal_assignment"):
            return Response({"detail": "Table not found."}, status=400)
        rec_id = request.query_params.get("id")
        if not rec_id:
            return Response({"detail": "id is required."}, status=400)
        if role == "Teacher":
            own = row("SELECT teacher_id FROM portal_assignment WHERE id=%s", [rec_id])
            if own and own["teacher_id"] != request.user.id:
                return Response({"detail": "You can only delete your own assignments."}, status=403)
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM portal_assignment WHERE id=%s RETURNING id", [rec_id])
            deleted = cursor.fetchone()
        if not deleted:
            return Response({"detail": "Not found."}, status=404)
        log_action(request.user, "assignment.delete", "portal_assignment", rec_id, {})
        return Response({"detail": "Deleted."})


# ---------------------------------------------------------------------------
# 3. Late Submission Policy
# ---------------------------------------------------------------------------
class LateSubmissionView(AdminMixin, APIView):
    """GET  — view late submission records and policy
    POST — configure late submission policy"""

    POLICY_TABLE = "portal_late_submission_policy"

    def _ensure_table(self):
        try:
            with connection.cursor() as cursor:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS public.portal_late_submission_policy (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        policy_name varchar(100) NOT NULL DEFAULT 'Default',
                        allow_late boolean DEFAULT true,
                        penalize_late boolean DEFAULT true,
                        penalty_percent numeric(5,2) DEFAULT 10.00,
                        max_late_days smallint DEFAULT 3,
                        block_after_max boolean DEFAULT false,
                        is_active boolean DEFAULT true,
                        updated_at timestamptz NOT NULL DEFAULT now(),
                        updated_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL
                    );
                """)
                cursor.execute("SELECT COUNT(*)::int FROM portal_late_submission_policy")
                if cursor.fetchone()[0] == 0:
                    cursor.execute(
                        "INSERT INTO portal_late_submission_policy (policy_name, allow_late, penalize_late, penalty_percent, max_late_days) "
                        "VALUES ('Default', true, true, 10.00, 3)"
                    )
        except Exception:
            pass

    def get(self, request):
        self._ensure_table()
        if not table_exists(self.POLICY_TABLE):
            return Response([])
        # List late submissions with policy context
        late_submissions = []
        if table_exists("portal_assignment_submission") and table_exists("portal_assignment"):
            late_submissions = rows(
                """
                SELECT sub.id AS submission_id, sub.assignment_id, sub.student_id, sub.submitted_at,
                       a.due_date, a.title AS assignment_title,
                       COALESCE(u.first_name || ' ' || u.last_name, u.username) AS student_name,
                       CASE WHEN sub.submitted_at > a.due_date THEN
                           EXTRACT(DAY FROM sub.submitted_at - a.due_date)::int
                       ELSE 0 END AS days_late
                FROM portal_assignment_submission sub
                JOIN portal_assignment a ON a.id = sub.assignment_id
                JOIN auth_user u ON u.id = sub.student_id
                WHERE sub.submitted_at > a.due_date
                ORDER BY sub.submitted_at DESC
                LIMIT 100
                """
            )
        policy = rows("SELECT * FROM portal_late_submission_policy ORDER BY id") if table_exists(self.POLICY_TABLE) else []
        return Response(serialise({"policy": policy, "late_submissions": late_submissions}))

    def post(self, request):
        self._ensure_table()
        if not table_exists(self.POLICY_TABLE):
            return Response({"detail": "Policy table not found."}, status=400)
        d = request.data
        rec_id = d.get("id")
        with connection.cursor() as cursor:
            if rec_id:
                cursor.execute(
                    "UPDATE portal_late_submission_policy SET "
                    "policy_name=%s, allow_late=%s, penalize_late=%s, penalty_percent=%s, "
                    "max_late_days=%s, block_after_max=%s, is_active=%s, updated_at=now(), updated_by=%s WHERE id=%s",
                    [d.get("policy_name", "Default"), d.get("allow_late", True), d.get("penalize_late", True),
                     d.get("penalty_percent", 10), d.get("max_late_days", 3), d.get("block_after_max", False),
                     d.get("is_active", True), request.user.id, rec_id],
                )
                log_action(request.user, "late_policy.update", self.POLICY_TABLE, rec_id, d)
                return Response({"detail": "Policy updated."})
            else:
                cursor.execute(
                    "INSERT INTO portal_late_submission_policy "
                    "(policy_name, allow_late, penalize_late, penalty_percent, max_late_days, block_after_max, updated_by) "
                    "VALUES (%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                    [d.get("policy_name", "Default"), d.get("allow_late", True), d.get("penalize_late", True),
                     d.get("penalty_percent", 10), d.get("max_late_days", 3), d.get("block_after_max", False),
                     request.user.id],
                )
                new_id = cursor.fetchone()[0]
                log_action(request.user, "late_policy.create", self.POLICY_TABLE, new_id, d)
                return Response({"id": new_id, "detail": "Policy created."}, status=201)


# ---------------------------------------------------------------------------
# 4. Resubmission Management
# ---------------------------------------------------------------------------
class ResubmissionView(AdminMixin, APIView):
    """GET  — list resubmission requests
    POST — approve or reject a resubmission"""

    def _ensure_table(self):
        try:
            with connection.cursor() as cursor:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS public.portal_resubmission_request (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        assignment_id integer NOT NULL REFERENCES public.portal_assignment(id) ON DELETE CASCADE,
                        student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
                        reason text NOT NULL DEFAULT '',
                        status varchar(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected')),
                        reviewed_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
                        reviewed_at timestamptz,
                        created_at timestamptz NOT NULL DEFAULT now()
                    );
                    CREATE INDEX IF NOT EXISTS idx_resubmission_assignment ON public.portal_resubmission_request(assignment_id);
                    CREATE INDEX IF NOT EXISTS idx_resubmission_student ON public.portal_resubmission_request(student_id);
                """)
        except Exception:
            pass

    def get(self, request):
        self._ensure_table()
        if not table_exists("portal_resubmission_request"):
            return Response([])
        sql = """
            SELECT rr.id, rr.assignment_id, rr.student_id, rr.reason, rr.status,
                   rr.reviewed_by, rr.reviewed_at, rr.created_at,
                   a.title AS assignment_title,
                   COALESCE(u.first_name || ' ' || u.last_name, u.username) AS student_name,
                   COALESCE(ub.first_name || ' ' || ub.last_name, ub.username) AS reviewed_by_name
            FROM portal_resubmission_request rr
            JOIN portal_assignment a ON a.id = rr.assignment_id
            JOIN auth_user u ON u.id = rr.student_id
            LEFT JOIN auth_user ub ON ub.id = rr.reviewed_by
        """
        status_filter = request.query_params.get("status")
        params = []
        if status_filter:
            sql += " WHERE rr.status = %s"
            params.append(status_filter)
        sql += " ORDER BY rr.created_at DESC"
        return Response(serialise(rows(sql, params)))

    def post(self, request):
        self._ensure_table()
        if not table_exists("portal_resubmission_request"):
            return Response({"detail": "Resubmission table not found."}, status=400)
        d = request.data
        req_id = d.get("id")
        action = d.get("action")  # approve or reject
        if not req_id or action not in ("approve", "reject"):
            return Response({"detail": "id and action (approve/reject) are required."}, status=400)
        existing = row("SELECT id, status FROM portal_resubmission_request WHERE id=%s", [req_id])
        if not existing:
            return Response({"detail": "Request not found."}, status=404)
        if existing["status"] != "Pending":
            return Response({"detail": f"Request already {existing['status'].lower()}."}, status=400)
        new_status = "Approved" if action == "approve" else "Rejected"
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE portal_resubmission_request SET status=%s, reviewed_by=%s, reviewed_at=now() WHERE id=%s",
                [new_status, request.user.id, req_id],
            )
        log_action(request.user, f"resubmission.{action}", "portal_resubmission_request", req_id, {})
        return Response({"detail": f"Resubmission {action}d."})


# ---------------------------------------------------------------------------
# 5. Rubric Management
# ---------------------------------------------------------------------------
class RubricManagementView(AdminMixin, APIView):
    """GET  ?assignment_id= — list rubrics for an assignment
    POST — create rubric criteria
    PUT  — update rubric criteria
    DELETE ?id= — delete rubric criteria"""

    def get(self, request):
        _ensure_rubric_table()
        if not table_exists("portal_assignment_rubric"):
            return Response([])
        assignment_id = request.query_params.get("assignment_id")
        sql = """
            SELECT r.id, r.assignment_id, r.criterion, r.max_marks, r.description, r.sort_order, r.created_at,
                   a.title AS assignment_title
            FROM portal_assignment_rubric r
            JOIN portal_assignment a ON a.id = r.assignment_id
        """
        params = []
        if assignment_id:
            sql += " WHERE r.assignment_id = %s"
            params.append(assignment_id)
        sql += " ORDER BY r.sort_order ASC, r.id ASC"
        return Response(serialise(rows(sql, params)))

    def post(self, request):
        _ensure_rubric_table()
        if not table_exists("portal_assignment_rubric"):
            return Response({"detail": "Rubric table not found."}, status=400)
        d = request.data
        assignment_id = d.get("assignment_id")
        criterion = (d.get("criterion") or "").strip()
        if not assignment_id or not criterion:
            return Response({"detail": "assignment_id and criterion are required."}, status=400)
        # Verify assignment exists
        assign = row("SELECT id FROM portal_assignment WHERE id=%s", [assignment_id])
        if not assign:
            return Response({"detail": "Assignment not found."}, status=404)
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_assignment_rubric (assignment_id, criterion, max_marks, description, sort_order) "
                "VALUES (%s,%s,%s,%s,%s) RETURNING id",
                [assignment_id, criterion, d.get("max_marks", 10),
                 d.get("description", ""), d.get("sort_order", 0)],
            )
            new_id = cursor.fetchone()[0]
        log_action(request.user, "rubric.create", "portal_assignment_rubric", new_id, d)
        return Response({"id": new_id, "detail": "Rubric criterion created."}, status=201)

    def put(self, request):
        _ensure_rubric_table()
        if not table_exists("portal_assignment_rubric"):
            return Response({"detail": "Table not found."}, status=400)
        d = request.data
        rec_id = d.get("id")
        if not rec_id:
            return Response({"detail": "id is required."}, status=400)
        existing = row("SELECT id FROM portal_assignment_rubric WHERE id=%s", [rec_id])
        if not existing:
            return Response({"detail": "Not found."}, status=404)
        fields = []
        vals = []
        for col in ("criterion", "max_marks", "description", "sort_order"):
            if col in d:
                fields.append(f"{col} = %s")
                vals.append(d[col])
        if not fields:
            return Response({"detail": "No fields to update."}, status=400)
        vals.append(rec_id)
        with connection.cursor() as cursor:
            cursor.execute(f"UPDATE portal_assignment_rubric SET {', '.join(fields)} WHERE id = %s", vals)
        log_action(request.user, "rubric.update", "portal_assignment_rubric", rec_id, d)
        return Response({"detail": "Updated."})

    def delete(self, request):
        _ensure_rubric_table()
        if not table_exists("portal_assignment_rubric"):
            return Response({"detail": "Table not found."}, status=400)
        rec_id = request.query_params.get("id")
        if not rec_id:
            return Response({"detail": "id is required."}, status=400)
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM portal_assignment_rubric WHERE id=%s RETURNING id", [rec_id])
            deleted = cursor.fetchone()
        if not deleted:
            return Response({"detail": "Not found."}, status=404)
        log_action(request.user, "rubric.delete", "portal_assignment_rubric", rec_id, {})
        return Response({"detail": "Deleted."})


# ---------------------------------------------------------------------------
# 6. Assignment Reports
# ---------------------------------------------------------------------------
class AssignmentReportView(AdminMixin, APIView):
    """GET ?type=&class_id=&subject_id=&teacher_id=
    Supported types: pending, submitted, late, marks, class_performance,
    subject_performance, teacher_workload, completion_rate"""

    def get(self, request):
        report_type = request.query_params.get("type", "pending")
        class_id = request.query_params.get("class_id")
        subject_id = request.query_params.get("subject_id")
        teacher_id = request.query_params.get("teacher_id")

        if report_type == "pending":
            return self._pending_report(class_id, subject_id, teacher_id)
        elif report_type == "submitted":
            return self._submitted_report(class_id, subject_id, teacher_id)
        elif report_type == "late":
            return self._late_report(class_id, subject_id, teacher_id)
        elif report_type == "marks":
            return self._marks_report(class_id, subject_id, teacher_id)
        elif report_type == "class_performance":
            return self._class_performance_report()
        elif report_type == "subject_performance":
            return self._subject_performance_report()
        elif report_type == "teacher_workload":
            return self._teacher_workload_report()
        elif report_type == "completion_rate":
            return self._completion_rate_report(class_id, subject_id)
        return Response({"detail": f"Unknown report type '{report_type}'."}, status=400)

    def _pending_report(self, class_id, subject_id, teacher_id):
        if not table_exists("portal_assignment"):
            return Response([])
        sql = """
            SELECT a.id, a.title, a.due_date, a.max_marks, a.assignment_type,
                   s.name AS subject_name,
                   c.name || '-' || c.section AS class_name,
                   COALESCE(u.first_name || ' ' || u.last_name, u.username) AS teacher_name,
                   (SELECT COUNT(*)::int FROM portal_assignment_submission sub WHERE sub.assignment_id = a.id) AS submitted_count
            FROM portal_assignment a
            LEFT JOIN portal_subject s ON s.id = a.subject_id
            LEFT JOIN portal_class c ON c.id = a.class_id
            LEFT JOIN auth_user u ON u.id = a.teacher_id
            WHERE a.due_date >= now()
        """
        params = []
        if class_id:
            sql += " AND a.class_id = %s"
            params.append(class_id)
        if subject_id:
            sql += " AND a.subject_id = %s"
            params.append(subject_id)
        if teacher_id:
            sql += " AND a.teacher_id = %s"
            params.append(teacher_id)
        sql += " ORDER BY a.due_date ASC"
        return Response(serialise(rows(sql, params)))

    def _submitted_report(self, class_id, subject_id, teacher_id):
        if not table_exists("portal_assignment_submission"):
            return Response([])
        sql = """
            SELECT sub.id, sub.submission_url, sub.submitted_at, sub.marks_obtained, sub.grade,
                   a.title AS assignment_title, a.max_marks,
                   s.name AS subject_name,
                   COALESCE(u.first_name || ' ' || u.last_name, u.username) AS student_name,
                   COALESCE(ut.first_name || ' ' || ut.last_name, ut.username) AS teacher_name
            FROM portal_assignment_submission sub
            JOIN portal_assignment a ON a.id = sub.assignment_id
            JOIN auth_user u ON u.id = sub.student_id
            LEFT JOIN portal_subject s ON s.id = a.subject_id
            LEFT JOIN auth_user ut ON ut.id = a.teacher_id
            WHERE 1=1
        """
        params = []
        if class_id:
            sql += " AND a.class_id = %s"
            params.append(class_id)
        if subject_id:
            sql += " AND a.subject_id = %s"
            params.append(subject_id)
        if teacher_id:
            sql += " AND a.teacher_id = %s"
            params.append(teacher_id)
        sql += " ORDER BY sub.submitted_at DESC"
        return Response(serialise(rows(sql, params)))

    def _late_report(self, class_id, subject_id, teacher_id):
        if not table_exists("portal_assignment_submission") or not table_exists("portal_assignment"):
            return Response([])
        sql = """
            SELECT sub.id, sub.submitted_at, sub.marks_obtained,
                   a.title AS assignment_title, a.due_date,
                   s.name AS subject_name,
                   COALESCE(u.first_name || ' ' || u.last_name, u.username) AS student_name,
                   EXTRACT(DAY FROM sub.submitted_at - a.due_date)::int AS days_late
            FROM portal_assignment_submission sub
            JOIN portal_assignment a ON a.id = sub.assignment_id
            JOIN auth_user u ON u.id = sub.student_id
            LEFT JOIN portal_subject s ON s.id = a.subject_id
            WHERE sub.submitted_at > a.due_date
        """
        params = []
        if class_id:
            sql += " AND a.class_id = %s"
            params.append(class_id)
        if subject_id:
            sql += " AND a.subject_id = %s"
            params.append(subject_id)
        if teacher_id:
            sql += " AND a.teacher_id = %s"
            params.append(teacher_id)
        sql += " ORDER BY days_late DESC"
        return Response(serialise(rows(sql, params)))

    def _marks_report(self, class_id, subject_id, teacher_id):
        if not table_exists("portal_assignment_submission"):
            return Response([])
        sql = """
            SELECT sub.marks_obtained, sub.grade, sub.teacher_feedback,
                   a.title AS assignment_title, a.max_marks,
                   COALESCE(u.first_name || ' ' || u.last_name, u.username) AS student_name,
                   s.name AS subject_name
            FROM portal_assignment_submission sub
            JOIN portal_assignment a ON a.id = sub.assignment_id
            JOIN auth_user u ON u.id = sub.student_id
            LEFT JOIN portal_subject s ON s.id = a.subject_id
            WHERE sub.marks_obtained IS NOT NULL
        """
        params = []
        if class_id:
            sql += " AND a.class_id = %s"
            params.append(class_id)
        if subject_id:
            sql += " AND a.subject_id = %s"
            params.append(subject_id)
        if teacher_id:
            sql += " AND a.teacher_id = %s"
            params.append(teacher_id)
        sql += " ORDER BY sub.marks_obtained DESC"
        return Response(serialise(rows(sql, params)))

    def _class_performance_report(self):
        if not table_exists("portal_assignment") or not table_exists("portal_assignment_submission"):
            return Response([])
        data = rows(
            """
            SELECT c.id, c.name || '-' || c.section AS class_name,
                   COUNT(DISTINCT a.id)::int AS total_assignments,
                   COUNT(DISTINCT sub.id)::int AS total_submissions,
                   ROUND(COALESCE(AVG(sub.marks_obtained), 0)::numeric, 2) AS average_marks
            FROM portal_class c
            LEFT JOIN portal_assignment a ON a.class_id = c.id
            LEFT JOIN portal_assignment_submission sub ON sub.assignment_id = a.id
            GROUP BY c.id, c.name, c.section
            ORDER BY c.name, c.section
            """
        )
        return Response(serialise(data))

    def _subject_performance_report(self):
        if not table_exists("portal_assignment") or not table_exists("portal_assignment_submission"):
            return Response([])
        data = rows(
            """
            SELECT s.id, s.name AS subject_name,
                   COUNT(DISTINCT a.id)::int AS total_assignments,
                   COUNT(DISTINCT sub.id)::int AS total_submissions,
                   ROUND(COALESCE(AVG(sub.marks_obtained), 0)::numeric, 2) AS average_marks
            FROM portal_subject s
            LEFT JOIN portal_assignment a ON a.subject_id = s.id
            LEFT JOIN portal_assignment_submission sub ON sub.assignment_id = a.id
            GROUP BY s.id, s.name
            ORDER BY s.name
            """
        )
        return Response(serialise(data))

    def _teacher_workload_report(self):
        if not table_exists("portal_assignment"):
            return Response([])
        data = rows(
            """
            SELECT t.id AS teacher_id,
                   COALESCE(u.first_name || ' ' || u.last_name, u.username) AS teacher_name,
                   COUNT(DISTINCT a.id)::int AS total_assignments,
                   COUNT(DISTINCT sub.id)::int AS total_submissions,
                   MIN(a.created_at) AS first_assignment,
                   MAX(a.created_at) AS last_assignment
            FROM auth_user u
            JOIN portal_assignment a ON a.teacher_id = u.id
            LEFT JOIN portal_assignment_submission sub ON sub.assignment_id = a.id
            GROUP BY t.id, u.first_name, u.last_name, u.username
            ORDER BY total_assignments DESC
            """
        )
        return Response(serialise(data))

    def _completion_rate_report(self, class_id, subject_id):
        if not table_exists("portal_assignment"):
            return Response([])
        sql = """
            SELECT a.id, a.title, a.class_id, a.subject_id,
                   (SELECT COUNT(DISTINCT se.student_id) FROM portal_student_enrollment se WHERE se.class_id = a.class_id) AS enrolled,
                   (SELECT COUNT(*)::int FROM portal_assignment_submission sub WHERE sub.assignment_id = a.id) AS submitted
            FROM portal_assignment a WHERE 1=1
        """
        params = []
        if class_id:
            sql += " AND a.class_id = %s"
            params.append(class_id)
        if subject_id:
            sql += " AND a.subject_id = %s"
            params.append(subject_id)
        sql += " ORDER BY a.due_date DESC"
        data = rows(sql, params)
        for d in data:
            enrolled = d.get("enrolled") or 0
            submitted = d.get("submitted") or 0
            d["completion_rate"] = round((submitted * 100.0 / enrolled), 1) if enrolled > 0 else 0
        return Response(serialise(data))


# ---------------------------------------------------------------------------
# 7. Assignment Analytics Dashboard
# ---------------------------------------------------------------------------
class AssignmentAnalyticsView(AdminMixin, APIView):
    """GET dashboard analytics: total assignments, pending, submitted,
    average_marks, completion_percentage."""

    def get(self, request):
        analytics = {}
        try:
            with connection.cursor() as cursor:
                if table_exists("portal_assignment"):
                    cursor.execute("SELECT COUNT(*)::int FROM portal_assignment")
                    analytics["total_assignments"] = cursor.fetchone()[0]
                else:
                    analytics["total_assignments"] = 0

                if table_exists("portal_assignment_submission"):
                    cursor.execute("SELECT COUNT(*)::int FROM portal_assignment_submission")
                    analytics["total_submissions"] = cursor.fetchone()[0]
                    cursor.execute("SELECT COALESCE(AVG(marks_obtained), 0)::numeric(7,2) FROM portal_assignment_submission WHERE marks_obtained IS NOT NULL")
                    analytics["average_marks"] = float(cursor.fetchone()[0])
                else:
                    analytics["total_submissions"] = 0
                    analytics["average_marks"] = 0

                if table_exists("portal_assignment"):
                    cursor.execute(
                        """
                        SELECT COUNT(DISTINCT a.id)::int AS total,
                               COUNT(DISTINCT sub.id)::int AS with_submissions
                        FROM portal_assignment a
                        LEFT JOIN portal_assignment_submission sub ON sub.assignment_id = a.id
                        """
                    )
                    counts = cursor.fetchone()
                    total = counts[0] or 0
                    with_sub = counts[1] or 0
                    analytics["pending"] = total - with_sub
                    analytics["submitted"] = with_sub
                    analytics["completion_percentage"] = round((with_sub * 100.0 / total), 1) if total > 0 else 0
                else:
                    analytics["pending"] = 0
                    analytics["submitted"] = 0
                    analytics["completion_percentage"] = 0

        except Exception:
            analytics = {
                "total_assignments": 0,
                "total_submissions": 0,
                "average_marks": 0,
                "pending": 0,
                "submitted": 0,
                "completion_percentage": 0,
            }
        return Response(serialise(analytics))


# ---------------------------------------------------------------------------
# 8. Assignment Notification
# ---------------------------------------------------------------------------
class AssignmentNotificationView(AdminMixin, APIView):
    """GET  — list assignment notifications
    POST — create notification
    DELETE ?id= — delete notification"""

    def _ensure_table(self):
        try:
            with connection.cursor() as cursor:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS public.portal_assignment_notification (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        assignment_id integer REFERENCES public.portal_assignment(id) ON DELETE SET NULL,
                        notification_type varchar(50) NOT NULL,
                        title varchar(255) NOT NULL,
                        message text NOT NULL,
                        target_audience varchar(30) DEFAULT 'all',
                        is_sent boolean DEFAULT false,
                        sent_at timestamptz,
                        created_at timestamptz NOT NULL DEFAULT now()
                    );
                    CREATE INDEX IF NOT EXISTS idx_assign_notif_assignment ON public.portal_assignment_notification(assignment_id);
                """)
        except Exception:
            pass

    def get(self, request):
        self._ensure_table()
        if not table_exists("portal_assignment_notification"):
            return Response([])
        assignment_id = request.query_params.get("assignment_id")
        sql = """
            SELECT an.id, an.assignment_id, an.notification_type, an.title, an.message,
                   an.target_audience, an.is_sent, an.sent_at, an.created_at,
                   a.title AS assignment_title
            FROM portal_assignment_notification an
            LEFT JOIN portal_assignment a ON a.id = an.assignment_id
        """
        params = []
        if assignment_id:
            sql += " WHERE an.assignment_id = %s"
            params.append(assignment_id)
        sql += " ORDER BY an.created_at DESC"
        return Response(serialise(rows(sql, params)))

    def post(self, request):
        self._ensure_table()
        if not table_exists("portal_assignment_notification"):
            return Response({"detail": "Notification table not found."}, status=400)
        d = request.data
        notification_type = (d.get("notification_type") or "").strip()
        title = (d.get("title") or "").strip()
        message = (d.get("message") or "").strip()
        if not notification_type or not title or not message:
            return Response({"detail": "notification_type, title, and message are required."}, status=400)
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_assignment_notification "
                "(assignment_id, notification_type, title, message, target_audience) "
                "VALUES (%s,%s,%s,%s,%s) RETURNING id",
                [d.get("assignment_id"), notification_type, title, message,
                 d.get("target_audience", "all")],
            )
            new_id = cursor.fetchone()[0]
        log_action(request.user, "assignment_notification.create", "portal_assignment_notification", new_id, d)
        return Response({"id": new_id, "detail": "Notification created."}, status=201)

    def delete(self, request):
        self._ensure_table()
        if not table_exists("portal_assignment_notification"):
            return Response({"detail": "Table not found."}, status=400)
        rec_id = request.query_params.get("id")
        if not rec_id:
            return Response({"detail": "id is required."}, status=400)
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM portal_assignment_notification WHERE id=%s RETURNING id", [rec_id])
            deleted = cursor.fetchone()
        if not deleted:
            return Response({"detail": "Not found."}, status=404)
        log_action(request.user, "assignment_notification.delete", "portal_assignment_notification", rec_id, {})
        return Response({"detail": "Deleted."})


# ---------------------------------------------------------------------------
# 9. Assignment Settings
# ---------------------------------------------------------------------------
class AssignmentSettingsView(AdminMixin, APIView):
    """GET  — global assignment settings
    POST — create or update settings"""

    SETTINGS_TABLE = "portal_assignment_settings"

    def _ensure_table(self):
        try:
            with connection.cursor() as cursor:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS public.portal_assignment_settings (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        setting_key varchar(100) NOT NULL UNIQUE,
                        setting_value text NOT NULL DEFAULT '',
                        description text DEFAULT '',
                        updated_at timestamptz NOT NULL DEFAULT now()
                    );
                """)
                # Seed defaults if empty
                cursor.execute("SELECT COUNT(*)::int FROM portal_assignment_settings")
                if cursor.fetchone()[0] == 0:
                    defaults = [
                        ("default_due_days", "7", "Default number of days until assignment is due"),
                        ("max_file_size_mb", "50", "Maximum file size in MB for submissions"),
                        ("allowed_file_types", "pdf,doc,docx,txt,jpg,png,zip", "Comma-separated allowed file types"),
                        ("late_policy", "penalize", "Late submission policy: allow/penalize/block"),
                        ("allow_resubmission", "true", "Whether resubmissions are allowed"),
                        ("max_resubmissions", "3", "Maximum number of resubmissions allowed"),
                        ("show_rubric_to_student", "true", "Whether rubric criteria are visible to students"),
                        ("auto_grade_quiz", "true", "Auto-grade quiz-type assignments"),
                    ]
                    for key, val, desc in defaults:
                        cursor.execute(
                            "INSERT INTO portal_assignment_settings (setting_key, setting_value, description) "
                            "VALUES (%s,%s,%s) ON CONFLICT DO NOTHING",
                            [key, val, desc],
                        )
        except Exception:
            pass

    def get(self, request):
        self._ensure_table()
        if not table_exists(self.SETTINGS_TABLE):
            return Response([])
        data = rows("SELECT * FROM portal_assignment_settings ORDER BY id")
        # Return as key-value dict for convenience
        settings = {d["setting_key"]: d["setting_value"] for d in data}
        return Response(serialise({"settings": settings, "raw": data}))

    def post(self, request):
        self._ensure_table()
        if not table_exists(self.SETTINGS_TABLE):
            return Response({"detail": "Settings table not found."}, status=400)
        d = request.data
        updates = d.get("settings") or d
        if not isinstance(updates, dict):
            return Response({"detail": "Provide settings as a key-value dict."}, status=400)
        updated_count = 0
        with connection.cursor() as cursor:
            for key, val in updates.items():
                if not key:
                    continue
                cursor.execute(
                    "INSERT INTO portal_assignment_settings (setting_key, setting_value, updated_at) "
                    "VALUES (%s,%s,now()) "
                    "ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value, updated_at=now()",
                    [str(key), str(val)],
                )
                updated_count += 1
        log_action(request.user, "assignment_settings.update", self.SETTINGS_TABLE, 0,
                   {"updated_keys": updated_count})
        return Response({"detail": f"{updated_count} setting(s) saved."})


# ---------------------------------------------------------------------------
# 10. Assignment Audit Log
# ---------------------------------------------------------------------------
class AssignmentAuditLogView(AdminMixin, APIView):
    """GET ?action=&assignment_id= — list assignment-related audit logs.
    Uses the global portal_audit_log table filtered by target_type."""

    def get(self, request):
        action_filter = request.query_params.get("action")
        assignment_id = request.query_params.get("assignment_id")

        if not table_exists("portal_audit_log"):
            return Response([])

        sql = """
            SELECT al.id, al.actor_id, al.action, al.target_type, al.target_id, al.details, al.created_at,
                   COALESCE(u.first_name || ' ' || u.last_name, u.username) AS actor_name
            FROM portal_audit_log al
            LEFT JOIN auth_user u ON u.id = al.actor_id
            WHERE al.target_type IN ('portal_assignment', 'portal_assignment_submission',
                                     'portal_assignment_rubric', 'portal_assignment_notification',
                                     'portal_assignment_category', 'portal_assignment_settings',
                                     'late_policy', 'rubric', 'resubmission',
                                     'assignment_category', 'assignment_notification',
                                     'assignment_settings')
        """
        params = []
        if action_filter:
            sql += " AND al.action = %s"
            params.append(action_filter)
        if assignment_id:
            sql += " AND al.target_id = %s"
            params.append(assignment_id)
        sql += " ORDER BY al.created_at DESC LIMIT 200"
        return Response(serialise(rows(sql, params)))
