# Generated by Django 5.0.6 on 2026-07-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_campus_options_alter_cmspage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='admissions_academic_year',
            field=models.CharField(default='2026-2027', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='admissions_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='admissions_open',
            field=models.BooleanField(default=True),
        ),
    ]
