-- EduNova Portal Extension – Complete Timetable Workflow
-- Run AFTER portal_extension_auth_user.sql
-- Safe to run multiple times: every statement is IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.

-- ===========================================================================
-- 1. Academic Calendar (Phase 1)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_academic_calendar (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL,
  term_name varchar(50) DEFAULT 'Annual',
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_current boolean DEFAULT false,
  description text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_academic_calendar_year ON public.portal_academic_calendar(academic_year);

-- Calendar Events (holidays, exam days, events)
CREATE TABLE IF NOT EXISTS public.portal_calendar_event (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calendar_id integer REFERENCES public.portal_academic_calendar(id) ON DELETE CASCADE,
  event_date date NOT NULL,
  event_name varchar(200) NOT NULL,
  event_type varchar(30) NOT NULL DEFAULT 'Holiday',
  is_working_day boolean DEFAULT false,
  description text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_calendar_event_date ON public.portal_calendar_event(event_date);
CREATE INDEX IF NOT EXISTS idx_calendar_event_type ON public.portal_calendar_event(event_type);

-- ===========================================================================
-- 2. Working Days Configuration (Phase 2)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_working_day (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL,
  day_of_week varchar(10) NOT NULL CHECK (day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')),
  is_working boolean NOT NULL DEFAULT true,
  is_half_day boolean DEFAULT false,
  start_time time,
  end_time time,
  UNIQUE (academic_year, day_of_week)
);

-- ===========================================================================
-- 3. School Timings Configuration (Phase 3)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_school_timing (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL,
  day_type varchar(20) NOT NULL DEFAULT 'FullDay',
  opening_time time NOT NULL DEFAULT '08:30',
  closing_time time NOT NULL DEFAULT '16:00',
  assembly_time time DEFAULT '08:30',
  lunch_start time DEFAULT '12:30',
  lunch_end time DEFAULT '13:15',
  tea_break_start time,
  tea_break_end time,
  UNIQUE (academic_year, day_type)
);

-- ===========================================================================
-- 4. Period Management (Phase 4)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_period (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL,
  period_number smallint NOT NULL,
  period_name varchar(50) DEFAULT '',
  start_time time NOT NULL,
  end_time time NOT NULL,
  is_break boolean DEFAULT false,
  break_label varchar(50) DEFAULT '',
  day_type varchar(20) DEFAULT 'FullDay',
  is_active boolean DEFAULT true,
  UNIQUE (academic_year, period_number, day_type)
);

-- ===========================================================================
-- 5. Subject Allocation per Class (Phase 6)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_subject_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  weekly_periods smallint DEFAULT 1,
  is_mandatory boolean DEFAULT true,
  is_elective boolean DEFAULT false,
  UNIQUE (academic_year, class_id, subject_id)
);

-- ===========================================================================
-- 6. Teacher Allocation per Class-Subject (Phase 7)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_teacher_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  max_periods_per_week smallint DEFAULT 30,
  UNIQUE (academic_year, class_id, subject_id, teacher_id)
);

-- ===========================================================================
-- 7. Classroom Allocation (Phase 8)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_classroom_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  room_number varchar(50) NOT NULL,
  room_type varchar(30) DEFAULT 'Classroom',
  capacity integer DEFAULT 40,
  is_lab boolean DEFAULT false,
  UNIQUE (academic_year, class_id, room_number)
);

-- ===========================================================================
-- 8. Lab Timetable override (Phase 9)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_lab_timetable (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_timetable_id integer REFERENCES public.portal_timetable(id) ON DELETE CASCADE,
  lab_room varchar(50) NOT NULL,
  teacher_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  day_of_week varchar(10) NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  is_published boolean DEFAULT false
);

-- ===========================================================================
-- 9. Substitute Teacher Management (Phase 10)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_substitute (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timetable_entry_id integer REFERENCES public.portal_timetable(id) ON DELETE CASCADE,
  original_teacher_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  substitute_teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  substitute_date date NOT NULL,
  reason varchar(200) DEFAULT '',
  is_notified boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- 10. Timetable Approval Workflow (Phase 12)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_timetable_approval (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  academic_year varchar(10) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'Draft',
  submitted_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  approved_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  rejection_reason text DEFAULT '',
  submitted_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (class_id, academic_year)
);

-- ===========================================================================
-- 11. Timetable Notifications (Phase 14)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_timetable_notification (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer REFERENCES public.portal_class(id) ON DELETE CASCADE,
  notification_type varchar(50) NOT NULL,
  title varchar(255) NOT NULL,
  message text NOT NULL,
  target_audience varchar(30) DEFAULT 'all',
  is_sent boolean DEFAULT false,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- 12. Timetable Audit Logs (Phase 20)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.portal_timetable_audit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer REFERENCES public.portal_class(id) ON DELETE SET NULL,
  academic_year varchar(10),
  action varchar(50) NOT NULL,
  action_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  details jsonb DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_timetable_audit_class ON public.portal_timetable_audit(class_id);
CREATE INDEX IF NOT EXISTS idx_timetable_audit_action ON public.portal_timetable_audit(action);

-- ===========================================================================
-- Add new columns to existing portal_timetable (Phase 5 base table)
-- ===========================================================================
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS academic_year varchar(10) NOT NULL DEFAULT '2025-26';
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS is_published boolean NOT NULL DEFAULT false;
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS period_label varchar(50) DEFAULT '';
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS room_type varchar(30) DEFAULT 'Classroom';
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS approval_status varchar(20) DEFAULT 'Draft';
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS is_lab_session boolean DEFAULT false;
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS is_substituted boolean DEFAULT false;
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- Drop existing unique constraint if it exists and re-create with our schema
ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS period_number smallint;
ALTER TABLE public.portal_timetable DROP CONSTRAINT IF EXISTS portal_timetable_class_id_day_of_week_start_time_key;
ALTER TABLE public.portal_timetable DROP CONSTRAINT IF EXISTS portal_timetable_unique_entry;
ALTER TABLE public.portal_timetable ADD CONSTRAINT portal_timetable_unique_entry
  UNIQUE NULLS NOT DISTINCT (class_id, day_of_week, start_time, academic_year, period_number);

-- Additional indexes for timetable performance
CREATE INDEX IF NOT EXISTS idx_timetable_approval_status ON public.portal_timetable(approval_status);
CREATE INDEX IF NOT EXISTS idx_timetable_academic_year ON public.portal_timetable(academic_year);
CREATE INDEX IF NOT EXISTS idx_timetable_is_lab ON public.portal_timetable(is_lab_session);
