-- =============================================================================
-- EduNova Examination Management Module — Schema Extension
-- =============================================================================
-- This migration extends the existing examination tables and adds new tables
-- for: exam types, subject config per exam, seating, invigilator allocation,
-- hall ticket config, marks verification, grade config, exam notifications,
-- and audit logs.
--
-- Safe to re-run: every statement uses IF NOT EXISTS / IF EXISTS guards.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. NEW TABLE: portal_exam_type
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_exam_type (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL UNIQUE,
  description text DEFAULT '',
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true
);

INSERT INTO public.portal_exam_type (name, description, sort_order) VALUES
  ('Unit_Test', 'Short assessments after each unit', 1),
  ('Weekly_Test', 'Weekly progress tests', 2),
  ('Monthly_Test', 'Monthly cumulative tests', 3),
  ('Quarterly', 'End of quarter examinations', 4),
  ('Half_Yearly', 'Mid-year comprehensive assessment', 5),
  ('Annual', 'End of year final examination', 6),
  ('Mid_Term', 'Mid-term assessment', 7),
  ('Practical', 'Hands-on lab-based assessment', 8),
  ('Viva', 'Oral examination', 9),
  ('Online_Assessment', 'Digital/online examination', 10),
  ('Mock_Test', 'Pre-board practice test', 11),
  ('Supplementary', 'Re-examination for failed subjects', 12)
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. NEW TABLE: portal_exam_subject
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_exam_subject (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  exam_date date,
  start_time time,
  duration_minutes smallint DEFAULT 180,
  max_marks smallint DEFAULT 100,
  passing_marks smallint DEFAULT 35,
  UNIQUE (exam_schedule_id, subject_id)
);

-- ---------------------------------------------------------------------------
-- 3. NEW TABLE: portal_seating_arrangement
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_seating_arrangement (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  room_name varchar(50) NOT NULL,
  seat_number varchar(20) NOT NULL,
  UNIQUE (exam_schedule_id, student_id)
);

-- ---------------------------------------------------------------------------
-- 4. NEW TABLE: portal_invigilator_allocation
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_invigilator_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  room_name varchar(50) NOT NULL,
  exam_date date,
  start_time time,
  end_time time,
  UNIQUE (exam_schedule_id, teacher_id, room_name)
);

-- ---------------------------------------------------------------------------
-- 5. NEW TABLE: portal_marks_verification
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_marks_verification (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id integer NOT NULL REFERENCES public.portal_result(id) ON DELETE CASCADE,
  verified_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  verified_at timestamptz NOT NULL DEFAULT now(),
  is_verified boolean DEFAULT true,
  remarks text DEFAULT ''
);

-- ---------------------------------------------------------------------------
-- 6. NEW TABLE: portal_grade_config
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_grade_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL DEFAULT '2025-26',
  grade_letter varchar(5) NOT NULL,
  min_percentage numeric(5,2) NOT NULL,
  max_percentage numeric(5,2) NOT NULL,
  grade_points numeric(4,2) NOT NULL,
  description varchar(100) DEFAULT '',
  UNIQUE (academic_year, grade_letter)
);

INSERT INTO public.portal_grade_config (academic_year, grade_letter, min_percentage, max_percentage, grade_points, description) VALUES
  ('2025-26', 'A+', 90, 100, 10, 'Outstanding'),
  ('2025-26', 'A', 80, 89.99, 9, 'Excellent'),
  ('2025-26', 'B+', 70, 79.99, 8, 'Very Good'),
  ('2025-26', 'B', 60, 69.99, 7, 'Good'),
  ('2025-26', 'C+', 50, 59.99, 6, 'Above Average'),
  ('2025-26', 'C', 40, 49.99, 5, 'Average'),
  ('2025-26', 'D', 35, 39.99, 4, 'Pass'),
  ('2025-26', 'E', 0, 34.99, 0, 'Fail')
ON CONFLICT (academic_year, grade_letter) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 7. NEW TABLE: portal_hall_ticket_config
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_hall_ticket_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL DEFAULT '2025-26',
  require_fee_clearance boolean DEFAULT true,
  require_min_attendance boolean DEFAULT true,
  min_attendance_percent numeric(5,2) DEFAULT 75.00,
  instructions text DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.portal_hall_ticket_config (academic_year) VALUES ('2025-26') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 8. NEW TABLE: portal_exam_notification
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_exam_notification (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  notification_type varchar(50) NOT NULL,
  title varchar(255) NOT NULL,
  message text NOT NULL,
  target_audience varchar(30) DEFAULT 'all',
  is_sent boolean DEFAULT false,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 9. NEW TABLE: portal_exam_audit
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_exam_audit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer REFERENCES public.portal_exam_schedule(id) ON DELETE SET NULL,
  action varchar(50) NOT NULL,
  action_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  details jsonb DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 10. ALTER existing tables — add new columns
-- ---------------------------------------------------------------------------

-- portal_exam_schedule
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS is_practical boolean DEFAULT false;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS is_online boolean DEFAULT false;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS internal_marks smallint DEFAULT 0;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS practical_marks smallint DEFAULT 0;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS created_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS approved_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS approved_at timestamptz;

-- portal_result
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false;
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS total_marks smallint DEFAULT 0;
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS percentage numeric(5,2);
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS pass_fail varchar(10) DEFAULT 'Pending';
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- portal_hall_ticket
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS generated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS downloaded_at timestamptz;
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS fee_cleared boolean DEFAULT false;
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS attendance_ok boolean DEFAULT false;

-- portal_question_bank (ensure columns from original schema)
ALTER TABLE public.portal_question_bank ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

-- portal_question_paper (ensure columns from original schema)
ALTER TABLE public.portal_question_paper ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

-- portal_revaluation_request (ensure columns from original schema)
ALTER TABLE public.portal_revaluation_request ADD COLUMN IF NOT EXISTS requested_at timestamptz NOT NULL DEFAULT now();

-- portal_supplementary_registration (ensure columns from original schema)
ALTER TABLE public.portal_supplementary_registration ADD COLUMN IF NOT EXISTS registered_at timestamptz NOT NULL DEFAULT now();

-- portal_academic_certificate (ensure columns from original schema)
ALTER TABLE public.portal_academic_certificate ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

-- portal_assignment (ensure assignment_type column)
ALTER TABLE public.portal_assignment ADD COLUMN IF NOT EXISTS assignment_type varchar(50) DEFAULT 'Assignment';
ALTER TABLE public.portal_assignment ADD COLUMN IF NOT EXISTS quiz_questions jsonb DEFAULT '[]'::jsonb;

-- portal_assignment_submission (ensure columns)
ALTER TABLE public.portal_assignment_submission ADD COLUMN IF NOT EXISTS submitted_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_assignment_submission ADD COLUMN IF NOT EXISTS marks_obtained numeric;
ALTER TABLE public.portal_assignment_submission ADD COLUMN IF NOT EXISTS teacher_feedback text DEFAULT '';
ALTER TABLE public.portal_assignment_submission ADD COLUMN IF NOT EXISTS grade varchar(10);

-- portal_homework (ensure columns)
ALTER TABLE public.portal_homework ADD COLUMN IF NOT EXISTS assigned_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.portal_homework ADD COLUMN IF NOT EXISTS due_date date;

-- ---------------------------------------------------------------------------
-- 11. INDEXES for performance
-- ---------------------------------------------------------------------------

-- Exam type lookup
CREATE INDEX IF NOT EXISTS idx_exam_type_active ON public.portal_exam_type(is_active);

-- Exam subject by schedule
CREATE INDEX IF NOT EXISTS idx_exam_subject_schedule ON public.portal_exam_subject(exam_schedule_id);

-- Seating by exam
CREATE INDEX IF NOT EXISTS idx_seating_exam ON public.portal_seating_arrangement(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_seating_student ON public.portal_seating_arrangement(student_id);

-- Invigilator allocation by exam
CREATE INDEX IF NOT EXISTS idx_invigilator_exam ON public.portal_invigilator_allocation(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_invigilator_teacher ON public.portal_invigilator_allocation(teacher_id);

-- Marks verification by result
CREATE INDEX IF NOT EXISTS idx_marks_verification_result ON public.portal_marks_verification(result_id);

-- Grade config by year
CREATE INDEX IF NOT EXISTS idx_grade_config_year ON public.portal_grade_config(academic_year);

-- Exam notification by schedule
CREATE INDEX IF NOT EXISTS idx_exam_notification_schedule ON public.portal_exam_notification(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_exam_notification_sent ON public.portal_exam_notification(is_sent);

-- Exam audit by schedule and action
CREATE INDEX IF NOT EXISTS idx_exam_audit_schedule ON public.portal_exam_audit(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_exam_audit_action ON public.portal_exam_audit(action);
CREATE INDEX IF NOT EXISTS idx_exam_audit_by ON public.portal_exam_audit(action_by);

-- Exam schedule additional indexes
CREATE INDEX IF NOT EXISTS idx_exam_schedule_practical ON public.portal_exam_schedule(is_practical);
CREATE INDEX IF NOT EXISTS idx_exam_schedule_online ON public.portal_exam_schedule(is_online);
CREATE INDEX IF NOT EXISTS idx_exam_schedule_created_by ON public.portal_exam_schedule(created_by);

-- Result indexes
CREATE INDEX IF NOT EXISTS idx_result_verified ON public.portal_result(is_verified);
CREATE INDEX IF NOT EXISTS idx_result_pass_fail ON public.portal_result(pass_fail);
CREATE INDEX IF NOT EXISTS idx_result_percentage ON public.portal_result(percentage);

-- Hall ticket indexes
CREATE INDEX IF NOT EXISTS idx_hall_ticket_generated ON public.portal_hall_ticket(generated_at);
CREATE INDEX IF NOT EXISTS idx_hall_ticket_fee ON public.portal_hall_ticket(fee_cleared);

-- Assignment extra indexes
CREATE INDEX IF NOT EXISTS idx_assignment_type ON public.portal_assignment(assignment_type);
CREATE INDEX IF NOT EXISTS idx_assignment_submission_submitted ON public.portal_assignment_submission(submitted_at);

-- ===========================================================================
-- 12. GAP FIXES — Missing tables for 25-submodule spec
-- ===========================================================================

-- portal_question_paper (missing CREATE TABLE)
CREATE TABLE IF NOT EXISTS public.portal_question_paper (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  title varchar(255) NOT NULL DEFAULT '',
  paper_type varchar(30) DEFAULT 'Manual',
  questions jsonb DEFAULT '[]'::jsonb,
  status varchar(30) DEFAULT 'Draft',
  answer_key jsonb DEFAULT '{}'::jsonb,
  difficulty_distribution jsonb DEFAULT '{}'::jsonb,
  version smallint DEFAULT 1,
  is_locked boolean DEFAULT false,
  created_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- portal_revaluation_request (missing CREATE TABLE)
CREATE TABLE IF NOT EXISTS public.portal_revaluation_request (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id integer NOT NULL REFERENCES public.portal_result(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  reason text NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'Pending',
  teacher_remarks text DEFAULT '',
  requested_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  updated_marks numeric,
  reviewed_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  UNIQUE (result_id)
);

-- portal_supplementary_registration (missing CREATE TABLE)
CREATE TABLE IF NOT EXISTS public.portal_supplementary_registration (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  original_exam_schedule_id integer REFERENCES public.portal_exam_schedule(id) ON DELETE SET NULL,
  status varchar(30) NOT NULL DEFAULT 'Registered',
  registered_at timestamptz NOT NULL DEFAULT now(),
  marks_obtained numeric,
  grade_letter varchar(10),
  is_paid boolean DEFAULT false,
  UNIQUE (student_id, subject_id, original_exam_schedule_id)
);

-- portal_academic_certificate (missing CREATE TABLE)
CREATE TABLE IF NOT EXISTS public.portal_academic_certificate (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  certificate_type varchar(50) NOT NULL,
  issued_date date NOT NULL DEFAULT CURRENT_DATE,
  file_url text DEFAULT '',
  verification_code varchar(100) UNIQUE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Exam Blueprint / Pattern Management (Submodule 8)
CREATE TABLE IF NOT EXISTS public.portal_exam_blueprint (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  question_type varchar(50) NOT NULL DEFAULT 'MCQ',
  question_count smallint DEFAULT 0,
  marks_per_question numeric(5,2) DEFAULT 0,
  total_marks numeric(6,2) DEFAULT 0,
  difficulty varchar(20) DEFAULT 'Medium',
  chapter varchar(100) DEFAULT '',
  UNIQUE (exam_schedule_id, subject_id, question_type, chapter)
);

-- Viva Examination records (Submodule 15)
CREATE TABLE IF NOT EXISTS public.portal_viva_exam (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  examiner_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  viva_date date DEFAULT CURRENT_DATE,
  topic varchar(255) DEFAULT '',
  questions_asked text DEFAULT '',
  marks_obtained numeric DEFAULT 0,
  max_marks numeric DEFAULT 25,
  remarks text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (exam_schedule_id, student_id)
);

-- Exam Attendance Tracking (Submodule 16)
CREATE TABLE IF NOT EXISTS public.portal_exam_attendance (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  attendance_status varchar(30) NOT NULL DEFAULT 'Present',
  check_in_time timestamptz,
  remarks text DEFAULT '',
  marked_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (exam_schedule_id, student_id)
);

-- Malpractice Register
CREATE TABLE IF NOT EXISTS public.portal_malpractice_register (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  incident_description text NOT NULL,
  evidence text DEFAULT '',
  reported_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  action_taken varchar(100) DEFAULT '',
  status varchar(30) DEFAULT 'Reported',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Improvement Exam Registration
CREATE TABLE IF NOT EXISTS public.portal_improvement_exam (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  original_result_id integer REFERENCES public.portal_result(id) ON DELETE SET NULL,
  new_exam_schedule_id integer REFERENCES public.portal_exam_schedule(id) ON DELETE SET NULL,
  status varchar(30) DEFAULT 'Registered',
  registered_at timestamptz NOT NULL DEFAULT now(),
  marks_obtained numeric,
  grade varchar(10),
  is_paid boolean DEFAULT false,
  remarks text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, subject_id)
);

-- ===========================================================================
-- 13. Additional ALTERs for gap columns
-- ===========================================================================

-- portal_exam_schedule: missing columns that code references
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS passing_marks smallint DEFAULT 35;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS room_name varchar(50) DEFAULT '';
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS invigilator_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS internal_weightage smallint DEFAULT 0;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS practical_weightage smallint DEFAULT 0;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS theory_marks smallint DEFAULT 0;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS external_marks smallint DEFAULT 0;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS cgpa numeric(4,2);
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS blueprint_id integer;

-- portal_hall_ticket: QR code
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS qr_code_url text DEFAULT '';
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS building varchar(50) DEFAULT '';
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS floor varchar(20) DEFAULT '';
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS bench_number varchar(20) DEFAULT '';
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS instructions text DEFAULT '';

-- portal_result: CGPA + grade_point
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS cgpa numeric(4,2);
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS grade_point numeric(4,2);
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS theory_marks_obtained numeric DEFAULT 0;
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS practical_marks_obtained numeric DEFAULT 0;
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS internal_marks_obtained numeric DEFAULT 0;
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS external_marks_obtained numeric DEFAULT 0;

-- portal_seating_arrangement: building/floor/bench
ALTER TABLE public.portal_seating_arrangement ADD COLUMN IF NOT EXISTS building varchar(50) DEFAULT '';
ALTER TABLE public.portal_seating_arrangement ADD COLUMN IF NOT EXISTS floor varchar(20) DEFAULT '';
ALTER TABLE public.portal_seating_arrangement ADD COLUMN IF NOT EXISTS bench_number varchar(20) DEFAULT '';
ALTER TABLE public.portal_seating_arrangement ADD COLUMN IF NOT EXISTS capacity smallint DEFAULT 0;

-- Improvement exam type seed data
INSERT INTO public.portal_exam_type (name, description, sort_order) VALUES
  ('Improvement', 'Examination for students seeking grade improvement', 13)
ON CONFLICT (name) DO NOTHING;

-- Grade config for CGPA calculation
ALTER TABLE public.portal_grade_config ADD COLUMN IF NOT EXISTS cgpa_value numeric(4,2) DEFAULT 0;
UPDATE public.portal_grade_config SET cgpa_value = grade_points / 2.5 WHERE cgpa_value = 0;

-- ===========================================================================
-- 14. Additional indexes
-- ===========================================================================
CREATE INDEX IF NOT EXISTS idx_exam_blueprint_schedule ON public.portal_exam_blueprint(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_viva_schedule ON public.portal_viva_exam(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_exam_attendance_schedule ON public.portal_exam_attendance(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_exam_attendance_status ON public.portal_exam_attendance(attendance_status);
CREATE INDEX IF NOT EXISTS idx_malpractice_schedule ON public.portal_malpractice_register(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_improvement_student ON public.portal_improvement_exam(student_id);
CREATE INDEX IF NOT EXISTS idx_question_paper_schedule ON public.portal_question_paper(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_revaluation_student ON public.portal_revaluation_request(student_id);
CREATE INDEX IF NOT EXISTS idx_supplementary_student ON public.portal_supplementary_registration(student_id);
CREATE INDEX IF NOT EXISTS idx_certificate_student ON public.portal_academic_certificate(student_id);
