-- Exam Extension Schema

-- 1. Alter portal_exam_schedule to add seating, invigilation, passing criteria, and assessment weightage
ALTER TABLE public.portal_exam_schedule 
  ADD COLUMN IF NOT EXISTS room_name varchar(100),
  ADD COLUMN IF NOT EXISTS invigilator_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS passing_marks integer NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS internal_weightage integer NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS practical_weightage integer NOT NULL DEFAULT 0;

-- 2. Question Bank
CREATE TABLE IF NOT EXISTS public.portal_question_bank (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  question_text text NOT NULL,
  type varchar(50) NOT NULL CHECK (type IN ('MCQ', 'Descriptive', 'Short', 'Practical')),
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  correct_answer text NOT NULL,
  difficulty varchar(50) NOT NULL CHECK (difficulty IN ('Easy', 'Medium', 'Hard')),
  chapter varchar(255) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. Question Paper
CREATE TABLE IF NOT EXISTS public.portal_question_paper (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer UNIQUE NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  title varchar(200) NOT NULL,
  paper_type varchar(50) NOT NULL CHECK (paper_type IN ('Manual', 'Auto')),
  questions jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  status varchar(50) NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'Published'))
);

-- 4. Revaluation Request
CREATE TABLE IF NOT EXISTS public.portal_revaluation_request (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id integer UNIQUE NOT NULL REFERENCES public.portal_result(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  reason text NOT NULL,
  status varchar(50) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Completed')),
  teacher_remarks text,
  requested_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  updated_marks numeric
);

-- 5. Supplementary Exam Registration
CREATE TABLE IF NOT EXISTS public.portal_supplementary_registration (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  original_exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  status varchar(50) NOT NULL DEFAULT 'Registered' CHECK (status IN ('Registered', 'Hall Ticket Issued', 'Absent', 'Completed')),
  registered_at timestamptz NOT NULL DEFAULT now(),
  marks_obtained numeric,
  grade_letter varchar(10)
);

-- 6. Academic Certificates
CREATE TABLE IF NOT EXISTS public.portal_academic_certificate (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  certificate_type varchar(100) NOT NULL CHECK (certificate_type IN ('Marks Memo', 'Pass Certificate', 'Rank Certificate', 'Provisional Certificate')),
  issued_date date NOT NULL DEFAULT CURRENT_DATE,
  file_url varchar(500),
  verification_code varchar(100) UNIQUE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
