-- ============================================================
-- EduNova – Fee Management Module Extension
-- Run AFTER portal_extension_auth_user.sql
-- ============================================================

-- Academic Year
CREATE TABLE IF NOT EXISTS public.portal_academic_year (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      varchar(20) NOT NULL UNIQUE,          -- e.g. "2025-26"
  start_date date NOT NULL,
  end_date   date NOT NULL,
  is_active  boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Fee Category master (configurable per school)
CREATE TABLE IF NOT EXISTS public.portal_fee_category (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        varchar(100) NOT NULL UNIQUE,        -- Tuition, Admission, Transport …
  description text,
  is_active   boolean NOT NULL DEFAULT true,
  sort_order  integer NOT NULL DEFAULT 0
);

-- Seed default categories
INSERT INTO public.portal_fee_category (name, description, sort_order) VALUES
  ('Tuition',       'Regular tuition / class fee',            1),
  ('Admission',     'One-time admission / registration fee',  2),
  ('Transport',     'School bus / vehicle fee',               3),
  ('Hostel',        'Hostel accommodation fee',               4),
  ('Library',       'Library membership & resource fee',      5),
  ('Examination',   'Exam hall, paper & evaluation fee',      6),
  ('Miscellaneous', 'Any other charges',                      7)
ON CONFLICT (name) DO NOTHING;

-- Extend fee_structure (add columns if missing)
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS academic_year_id integer REFERENCES public.portal_academic_year(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS due_date          date,
  ADD COLUMN IF NOT EXISTS late_fine_per_day numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_published      boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS description       text,
  ADD COLUMN IF NOT EXISTS admission_fee     numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS library_fee       numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exam_fee          numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS misc_fee          numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at        timestamptz NOT NULL DEFAULT now();

-- Student-level fee assignment (ties a student to a fee structure)
CREATE TABLE IF NOT EXISTS public.portal_fee_assignment (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id        integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  fee_structure_id  integer NOT NULL REFERENCES public.portal_fee_structure(id) ON DELETE CASCADE,
  assigned_by       integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  assigned_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, fee_structure_id)
);

-- Fee concession / scholarship / discount per student-structure pair
CREATE TABLE IF NOT EXISTS public.portal_fee_concession (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id        integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  fee_structure_id  integer NOT NULL REFERENCES public.portal_fee_structure(id) ON DELETE CASCADE,
  concession_type   varchar(50) NOT NULL DEFAULT 'Discount',  -- Scholarship | Sibling | Staff | Discount | Merit
  discount_amount   numeric NOT NULL DEFAULT 0,
  discount_percent  numeric NOT NULL DEFAULT 0,               -- alternative to flat amount
  reason            text,
  approved_by       integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, fee_structure_id)
);

-- Student fee ledger (computed/cached per student per structure)
CREATE TABLE IF NOT EXISTS public.portal_student_fee_ledger (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id        integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  fee_structure_id  integer NOT NULL REFERENCES public.portal_fee_structure(id) ON DELETE CASCADE,
  gross_amount      numeric NOT NULL DEFAULT 0,
  concession_amount numeric NOT NULL DEFAULT 0,
  fine_amount       numeric NOT NULL DEFAULT 0,
  net_payable       numeric NOT NULL DEFAULT 0,
  amount_paid       numeric NOT NULL DEFAULT 0,
  balance_due       numeric NOT NULL DEFAULT 0,
  status            varchar(30) NOT NULL DEFAULT 'Unpaid',   -- Unpaid | Partial | Paid | Overdue
  last_updated      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, fee_structure_id)
);

-- Extend portal_payment with extra fields
ALTER TABLE public.portal_payment
  ADD COLUMN IF NOT EXISTS payment_gateway_ref  varchar(200),
  ADD COLUMN IF NOT EXISTS fine_amount          numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS concession_amount    numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS receipt_number       varchar(100) UNIQUE;

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_fee_assignment_student ON public.portal_fee_assignment(student_id);
CREATE INDEX IF NOT EXISTS idx_fee_concession_student ON public.portal_fee_concession(student_id);
CREATE INDEX IF NOT EXISTS idx_fee_ledger_student     ON public.portal_student_fee_ledger(student_id);
CREATE INDEX IF NOT EXISTS idx_fee_structure_year     ON public.portal_fee_structure(academic_year_id);
