-- EduNova Portal Extension #6 — Full Hostel Management System
-- Run AFTER portal_extension_facilities.sql (portal_hostel, portal_room, portal_hostel_allocation must exist).
-- Safe to run multiple times: every statement is IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.

-- ---------------------------------------------------------------------------
-- Room & Allocation Table Modifications
-- ---------------------------------------------------------------------------
ALTER TABLE public.portal_room ADD COLUMN IF NOT EXISTS floor varchar(50) DEFAULT '1';
ALTER TABLE public.portal_room ADD COLUMN IF NOT EXISTS facilities text DEFAULT 'Basic Bed, Study Table';

ALTER TABLE public.portal_hostel_allocation ADD COLUMN IF NOT EXISTS mess_plan varchar(50) DEFAULT 'Veg Standard';

-- ---------------------------------------------------------------------------
-- Hostel Application (student requesting hostel entry)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_hostel_application (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  hostel_id integer NOT NULL REFERENCES public.portal_hostel(id) ON DELETE CASCADE,
  preferred_room_type varchar(50) DEFAULT '2-Sharing',
  reason text,
  status varchar(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
  reviewed_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  review_notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_hostel_app_student ON public.portal_hostel_application(student_id);
CREATE INDEX IF NOT EXISTS idx_hostel_app_status ON public.portal_hostel_application(status);

-- ---------------------------------------------------------------------------
-- Hostel Pass (identifies hostel residents)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_hostel_pass (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  pass_number varchar(50) NOT NULL UNIQUE,
  issued_at date NOT NULL DEFAULT CURRENT_DATE,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (student_id)
);
CREATE INDEX IF NOT EXISTS idx_hostel_pass_student ON public.portal_hostel_pass(student_id);

-- ---------------------------------------------------------------------------
-- Hostel Gate Passes / Leaves (night-outs, weekend trips, home visits)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_hostel_leave (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text NOT NULL,
  parent_approved boolean NOT NULL DEFAULT false,
  status varchar(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_hostel_leave_student ON public.portal_hostel_leave(student_id);
CREATE INDEX IF NOT EXISTS idx_hostel_leave_status ON public.portal_hostel_leave(status);

-- ---------------------------------------------------------------------------
-- Hostel Complaint Registry
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_hostel_complaint (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  category varchar(50) NOT NULL DEFAULT 'Maintenance',
  title varchar(150) NOT NULL,
  description text NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'In Progress', 'Resolved')),
  admin_notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_hostel_complaint_student ON public.portal_hostel_complaint(student_id);
CREATE INDEX IF NOT EXISTS idx_hostel_complaint_status ON public.portal_hostel_complaint(status);

-- ---------------------------------------------------------------------------
-- Hostel Fee (independent record per student per year)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_hostel_fee (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  academic_year varchar(20) NOT NULL DEFAULT to_char(now(), 'YYYY'),
  amount numeric(10,2) NOT NULL DEFAULT 0,
  amount_paid numeric(10,2) NOT NULL DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Paid', 'Partial')),
  due_date date,
  paid_at timestamptz,
  UNIQUE (student_id, academic_year)
);
CREATE INDEX IF NOT EXISTS idx_hostel_fee_student ON public.portal_hostel_fee(student_id);
