-- EduNova Portal Extension #5 — Campus Locations & Visit Booking
-- Safe to run multiple times: every statement is IF NOT EXISTS.

-- ---------------------------------------------------------------------------
-- Campus Location table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_campus_location (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL UNIQUE,
  address text NOT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(100) NOT NULL DEFAULT 'India',
  postal_code varchar(20) NOT NULL,
  latitude numeric(9, 6) NOT NULL,
  longitude numeric(9, 6) NOT NULL,
  phone varchar(30) NOT NULL,
  email varchar(100) NOT NULL,
  website varchar(200) NOT NULL,
  office_hours varchar(200) NOT NULL,
  facilities text[] NOT NULL DEFAULT '{}',
  programs text[] NOT NULL DEFAULT '{}',
  image_url text,
  status varchar(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  student_count integer NOT NULL DEFAULT 0,
  faculty_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Campus Visit booking table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_campus_visit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id integer REFERENCES public.portal_campus_location(id) ON DELETE CASCADE,
  visitor_name varchar(150) NOT NULL,
  visitor_email varchar(100) NOT NULL,
  visitor_phone varchar(30) NOT NULL,
  visit_date date NOT NULL,
  visit_time varchar(20) NOT NULL,
  purpose varchar(255),
  status varchar(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
