-- =============================================================================
-- EduNova Examination Management Module — Schema Extension
-- =============================================================================
-- This migration extends the existing examination tables and adds new tables
-- for: exam types, subject config per exam, seating, invigilator allocation,
-- hall ticket config, marks verification, grade config, exam notifications,
-- and audit logs.
--
-- Safe to re-run: every statement uses IF NOT EXISTS / IF EXISTS guards.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. NEW TABLE: portal_exam_type
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_exam_type (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL UNIQUE,
  description text DEFAULT '',
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true
);

INSERT INTO public.portal_exam_type (name, description, sort_order) VALUES
  ('Unit_Test', 'Short assessments after each unit', 1),
  ('Weekly_Test', 'Weekly progress tests', 2),
  ('Monthly_Test', 'Monthly cumulative tests', 3),
  ('Quarterly', 'End of quarter examinations', 4),
  ('Half_Yearly', 'Mid-year comprehensive assessment', 5),
  ('Annual', 'End of year final examination', 6),
  ('Mid_Term', 'Mid-term assessment', 7),
  ('Practical', 'Hands-on lab-based assessment', 8),
  ('Viva', 'Oral examination', 9),
  ('Online_Assessment', 'Digital/online examination', 10),
  ('Mock_Test', 'Pre-board practice test', 11),
  ('Supplementary', 'Re-examination for failed subjects', 12)
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. NEW TABLE: portal_exam_subject
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_exam_subject (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  exam_date date,
  start_time time,
  duration_minutes smallint DEFAULT 180,
  max_marks smallint DEFAULT 100,
  passing_marks smallint DEFAULT 35,
  UNIQUE (exam_schedule_id, subject_id)
);

-- ---------------------------------------------------------------------------
-- 3. NEW TABLE: portal_seating_arrangement
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_seating_arrangement (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  room_name varchar(50) NOT NULL,
  seat_number varchar(20) NOT NULL,
  UNIQUE (exam_schedule_id, student_id)
);

-- ---------------------------------------------------------------------------
-- 4. NEW TABLE: portal_invigilator_allocation
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_invigilator_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  room_name varchar(50) NOT NULL,
  exam_date date,
  start_time time,
  end_time time,
  UNIQUE (exam_schedule_id, teacher_id, room_name)
);

-- ---------------------------------------------------------------------------
-- 5. NEW TABLE: portal_marks_verification
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_marks_verification (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id integer NOT NULL REFERENCES public.portal_result(id) ON DELETE CASCADE,
  verified_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  verified_at timestamptz NOT NULL DEFAULT now(),
  is_verified boolean DEFAULT true,
  remarks text DEFAULT ''
);

-- ---------------------------------------------------------------------------
-- 6. NEW TABLE: portal_grade_config
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_grade_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL DEFAULT '2025-26',
  grade_letter varchar(5) NOT NULL,
  min_percentage numeric(5,2) NOT NULL,
  max_percentage numeric(5,2) NOT NULL,
  grade_points numeric(4,2) NOT NULL,
  description varchar(100) DEFAULT '',
  UNIQUE (academic_year, grade_letter)
);

INSERT INTO public.portal_grade_config (academic_year, grade_letter, min_percentage, max_percentage, grade_points, description) VALUES
  ('2025-26', 'A+', 90, 100, 10, 'Outstanding'),
  ('2025-26', 'A', 80, 89.99, 9, 'Excellent'),
  ('2025-26', 'B+', 70, 79.99, 8, 'Very Good'),
  ('2025-26', 'B', 60, 69.99, 7, 'Good'),
  ('2025-26', 'C+', 50, 59.99, 6, 'Above Average'),
  ('2025-26', 'C', 40, 49.99, 5, 'Average'),
  ('2025-26', 'D', 35, 39.99, 4, 'Pass'),
  ('2025-26', 'E', 0, 34.99, 0, 'Fail')
ON CONFLICT (academic_year, grade_letter) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 7. NEW TABLE: portal_hall_ticket_config
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_hall_ticket_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year varchar(10) NOT NULL DEFAULT '2025-26',
  require_fee_clearance boolean DEFAULT true,
  require_min_attendance boolean DEFAULT true,
  min_attendance_percent numeric(5,2) DEFAULT 75.00,
  instructions text DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.portal_hall_ticket_config (academic_year) VALUES ('2025-26') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 8. NEW TABLE: portal_exam_notification
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_exam_notification (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  notification_type varchar(50) NOT NULL,
  title varchar(255) NOT NULL,
  message text NOT NULL,
  target_audience varchar(30) DEFAULT 'all',
  is_sent boolean DEFAULT false,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 9. NEW TABLE: portal_exam_audit
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_exam_audit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_schedule_id integer REFERENCES public.portal_exam_schedule(id) ON DELETE SET NULL,
  action varchar(50) NOT NULL,
  action_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  details jsonb DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 10. ALTER existing tables — add new columns
-- ---------------------------------------------------------------------------

-- portal_exam_schedule
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS is_practical boolean DEFAULT false;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS is_online boolean DEFAULT false;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS internal_marks smallint DEFAULT 0;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS practical_marks smallint DEFAULT 0;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS created_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS approved_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL;
ALTER TABLE public.portal_exam_schedule ADD COLUMN IF NOT EXISTS approved_at timestamptz;

-- portal_result
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false;
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS total_marks smallint DEFAULT 0;
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS percentage numeric(5,2);
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS pass_fail varchar(10) DEFAULT 'Pending';
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_result ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- portal_hall_ticket
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS generated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS downloaded_at timestamptz;
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS fee_cleared boolean DEFAULT false;
ALTER TABLE public.portal_hall_ticket ADD COLUMN IF NOT EXISTS attendance_ok boolean DEFAULT false;

-- portal_question_bank (ensure columns from original schema)
ALTER TABLE public.portal_question_bank ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

-- portal_question_paper (ensure columns from original schema)
ALTER TABLE public.portal_question_paper ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

-- portal_revaluation_request (ensure columns from original schema)
ALTER TABLE public.portal_revaluation_request ADD COLUMN IF NOT EXISTS requested_at timestamptz NOT NULL DEFAULT now();

-- portal_supplementary_registration (ensure columns from original schema)
ALTER TABLE public.portal_supplementary_registration ADD COLUMN IF NOT EXISTS registered_at timestamptz NOT NULL DEFAULT now();

-- portal_academic_certificate (ensure columns from original schema)
ALTER TABLE public.portal_academic_certificate ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

-- portal_assignment (ensure assignment_type column)
ALTER TABLE public.portal_assignment ADD COLUMN IF NOT EXISTS assignment_type varchar(50) DEFAULT 'Assignment';
ALTER TABLE public.portal_assignment ADD COLUMN IF NOT EXISTS quiz_questions jsonb DEFAULT '[]'::jsonb;

-- portal_assignment_submission (ensure columns)
ALTER TABLE public.portal_assignment_submission ADD COLUMN IF NOT EXISTS submitted_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.portal_assignment_submission ADD COLUMN IF NOT EXISTS marks_obtained numeric;
ALTER TABLE public.portal_assignment_submission ADD COLUMN IF NOT EXISTS teacher_feedback text DEFAULT '';
ALTER TABLE public.portal_assignment_submission ADD COLUMN IF NOT EXISTS grade varchar(10);

-- portal_homework (ensure columns)
ALTER TABLE public.portal_homework ADD COLUMN IF NOT EXISTS assigned_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.portal_homework ADD COLUMN IF NOT EXISTS due_date date;

-- ---------------------------------------------------------------------------
-- 11. INDEXES for performance
-- ---------------------------------------------------------------------------

-- Exam type lookup
CREATE INDEX IF NOT EXISTS idx_exam_type_active ON public.portal_exam_type(is_active);

-- Exam subject by schedule
CREATE INDEX IF NOT EXISTS idx_exam_subject_schedule ON public.portal_exam_subject(exam_schedule_id);

-- Seating by exam
CREATE INDEX IF NOT EXISTS idx_seating_exam ON public.portal_seating_arrangement(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_seating_student ON public.portal_seating_arrangement(student_id);

-- Invigilator allocation by exam
CREATE INDEX IF NOT EXISTS idx_invigilator_exam ON public.portal_invigilator_allocation(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_invigilator_teacher ON public.portal_invigilator_allocation(teacher_id);

-- Marks verification by result
CREATE INDEX IF NOT EXISTS idx_marks_verification_result ON public.portal_marks_verification(result_id);

-- Grade config by year
CREATE INDEX IF NOT EXISTS idx_grade_config_year ON public.portal_grade_config(academic_year);

-- Exam notification by schedule
CREATE INDEX IF NOT EXISTS idx_exam_notification_schedule ON public.portal_exam_notification(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_exam_notification_sent ON public.portal_exam_notification(is_sent);

-- Exam audit by schedule and action
CREATE INDEX IF NOT EXISTS idx_exam_audit_schedule ON public.portal_exam_audit(exam_schedule_id);
CREATE INDEX IF NOT EXISTS idx_exam_audit_action ON public.portal_exam_audit(action);
CREATE INDEX IF NOT EXISTS idx_exam_audit_by ON public.portal_exam_audit(action_by);

-- Exam schedule additional indexes
CREATE INDEX IF NOT EXISTS idx_exam_schedule_practical ON public.portal_exam_schedule(is_practical);
CREATE INDEX IF NOT EXISTS idx_exam_schedule_online ON public.portal_exam_schedule(is_online);
CREATE INDEX IF NOT EXISTS idx_exam_schedule_created_by ON public.portal_exam_schedule(created_by);

-- Result indexes
CREATE INDEX IF NOT EXISTS idx_result_verified ON public.portal_result(is_verified);
CREATE INDEX IF NOT EXISTS idx_result_pass_fail ON public.portal_result(pass_fail);
CREATE INDEX IF NOT EXISTS idx_result_percentage ON public.portal_result(percentage);

-- Hall ticket indexes
CREATE INDEX IF NOT EXISTS idx_hall_ticket_generated ON public.portal_hall_ticket(generated_at);
CREATE INDEX IF NOT EXISTS idx_hall_ticket_fee ON public.portal_hall_ticket(fee_cleared);

-- Assignment extra indexes
CREATE INDEX IF NOT EXISTS idx_assignment_type ON public.portal_assignment(assignment_type);
CREATE INDEX IF NOT EXISTS idx_assignment_submission_submitted ON public.portal_assignment_submission(submitted_at);
