-- EduNova Portal Extension #5 — Full Transport Management System
-- Run AFTER portal_extension_parent_admin.sql (portal_vehicle, portal_route,
-- portal_transport_allocation, portal_live_bus_log, portal_employee must exist).
-- Safe to run multiple times: every statement is IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.

-- ---------------------------------------------------------------------------
-- Transport Driver profile (links a portal_employee/auth_user to a vehicle)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_transport_driver (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  license_number varchar(100),
  phone varchar(30),
  vehicle_id integer REFERENCES public.portal_vehicle(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (user_id)
);
CREATE INDEX IF NOT EXISTS idx_transport_driver_vehicle ON public.portal_transport_driver(vehicle_id);

-- ---------------------------------------------------------------------------
-- Transport Attendant profile (links to a route)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_transport_attendant (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  phone varchar(30),
  assigned_route_id integer REFERENCES public.portal_route(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (user_id)
);
CREATE INDEX IF NOT EXISTS idx_transport_attendant_route ON public.portal_transport_attendant(assigned_route_id);

-- ---------------------------------------------------------------------------
-- Pickup / Drop Points (ordered stops along a route)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_pickup_point (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id integer NOT NULL REFERENCES public.portal_route(id) ON DELETE CASCADE,
  name varchar(200) NOT NULL,
  sequence_order integer NOT NULL DEFAULT 1,
  pickup_time time,        -- morning school-ward
  drop_time time,          -- afternoon home-ward
  UNIQUE (route_id, name)
);
CREATE INDEX IF NOT EXISTS idx_pickup_point_route ON public.portal_pickup_point(route_id, sequence_order);

-- ---------------------------------------------------------------------------
-- Route → Vehicle assignment (many routes can share vehicles but at diff times;
-- this is a simple 1:1 "primary vehicle for a route" for Phase 1)
-- ---------------------------------------------------------------------------
ALTER TABLE public.portal_route ADD COLUMN IF NOT EXISTS vehicle_id integer REFERENCES public.portal_vehicle(id) ON DELETE SET NULL;
ALTER TABLE public.portal_route ADD COLUMN IF NOT EXISTS attendant_id integer REFERENCES public.portal_transport_attendant(id) ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- Transport Pass (unique pass per student, auto-generated number)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_transport_pass (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  pass_number varchar(50) NOT NULL UNIQUE,
  issued_at date NOT NULL DEFAULT CURRENT_DATE,
  valid_until date,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (student_id)
);
CREATE INDEX IF NOT EXISTS idx_transport_pass_student ON public.portal_transport_pass(student_id);

-- ---------------------------------------------------------------------------
-- Trip Log (per-vehicle-per-day trip tracking)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_trip_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id integer NOT NULL REFERENCES public.portal_vehicle(id) ON DELETE CASCADE,
  route_id integer REFERENCES public.portal_route(id) ON DELETE SET NULL,
  trip_date date NOT NULL DEFAULT CURRENT_DATE,
  started_at timestamptz,
  ended_at timestamptz,
  status varchar(30) NOT NULL DEFAULT 'Scheduled'
    CHECK (status IN ('Scheduled', 'In Progress', 'Completed', 'Cancelled')),
  started_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  notes text
);
CREATE INDEX IF NOT EXISTS idx_trip_log_vehicle_date ON public.portal_trip_log(vehicle_id, trip_date DESC);
CREATE INDEX IF NOT EXISTS idx_trip_log_date ON public.portal_trip_log(trip_date DESC);

-- ---------------------------------------------------------------------------
-- Transport Notifications / Alerts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_transport_notification (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id integer REFERENCES public.portal_vehicle(id) ON DELETE SET NULL,
  route_id integer REFERENCES public.portal_route(id) ON DELETE SET NULL,
  type varchar(50) NOT NULL DEFAULT 'Info'
    CHECK (type IN ('Bus Arrived', 'Delay Alert', 'Route Changed', 'Emergency', 'Info')),
  message text NOT NULL,
  created_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_transport_notification_created ON public.portal_transport_notification(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transport_notification_route ON public.portal_transport_notification(route_id);

-- ---------------------------------------------------------------------------
-- Transport Fee (simple standalone — per student transport fee status)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_transport_fee (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  academic_year varchar(20) NOT NULL DEFAULT to_char(now(), 'YYYY'),
  amount numeric(10,2) NOT NULL DEFAULT 0,
  amount_paid numeric(10,2) NOT NULL DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'Pending'
    CHECK (status IN ('Pending', 'Paid', 'Partial', 'Waived')),
  due_date date,
  paid_at timestamptz,
  UNIQUE (student_id, academic_year)
);
CREATE INDEX IF NOT EXISTS idx_transport_fee_student ON public.portal_transport_fee(student_id);

-- ---------------------------------------------------------------------------
-- Transport Settings (school-level configuration)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_transport_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key varchar(100) NOT NULL UNIQUE,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Seed default settings (safe to re-run via ON CONFLICT DO NOTHING)
INSERT INTO public.portal_transport_settings (key, value) VALUES
  ('contact_number', ''),
  ('annual_transport_fee', '0'),
  ('fee_due_date', ''),
  ('gps_update_interval_sec', '30'),
  ('published', 'false')
ON CONFLICT (key) DO NOTHING;
