-- EduNova Portal Extension – Academic Website Content
-- Run AFTER portal_extension_auth_user.sql
-- Safe to run multiple times: every statement is IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.

-- Academic Levels
CREATE TABLE IF NOT EXISTS public.portal_academic_level (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL UNIQUE,
  description text DEFAULT '',
  icon_name varchar(50) DEFAULT '',
  sort_order integer DEFAULT 0,
  is_published boolean DEFAULT true
);

INSERT INTO public.portal_academic_level (name, description, icon_name, sort_order) VALUES
  ('Pre-Primary', 'Foundational learning through play, creativity, and early confidence building for ages 3-5.', 'Baby', 1),
  ('Primary', 'Building strong academic foundations with reading, writing, arithmetic, and creative exploration.', 'BookOpen', 2),
  ('Middle School', 'Concept-based learning with projects, activities, and digital classroom support.', 'School', 3),
  ('Secondary', 'Structured academic preparation with subject mastery, assessments, and mentoring.', 'GraduationCap', 4),
  ('Senior Secondary', 'Focused academic pathways for higher education readiness and career direction.', 'Brain', 5)
ON CONFLICT (name) DO NOTHING;

-- Class Details (public-facing content for each portal_class)
CREATE TABLE IF NOT EXISTS public.portal_class_detail (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL UNIQUE REFERENCES public.portal_class(id) ON DELETE CASCADE,
  academic_level varchar(50) DEFAULT 'Primary',
  description text DEFAULT '',
  age_criteria varchar(100) DEFAULT '',
  student_teacher_ratio varchar(50) DEFAULT '',
  learning_objectives text DEFAULT '',
  academic_approach text DEFAULT '',
  facilities text DEFAULT '',
  activities text DEFAULT '',
  co_curricular text DEFAULT '',
  assessment_pattern text DEFAULT '',
  promotion_policy text DEFAULT '',
  learning_outcomes text DEFAULT '',
  cover_image_url text DEFAULT '',
  gallery_images text DEFAULT '',
  is_published boolean DEFAULT true,
  meta_title varchar(200) DEFAULT '',
  meta_description varchar(300) DEFAULT '',
  sort_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_class_detail_class ON public.portal_class_detail(class_id);
CREATE INDEX IF NOT EXISTS idx_class_detail_level ON public.portal_class_detail(academic_level);

-- Subject Details (public-facing content for each portal_subject)
CREATE TABLE IF NOT EXISTS public.portal_subject_detail (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL UNIQUE REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  description text DEFAULT '',
  learning_outcomes text DEFAULT '',
  teaching_methodology text DEFAULT '',
  activities text DEFAULT '',
  projects text DEFAULT '',
  assessment text DEFAULT '',
  recommended_books text DEFAULT '',
  cover_image_url text DEFAULT '',
  is_published boolean DEFAULT true,
  meta_title varchar(200) DEFAULT '',
  meta_description varchar(300) DEFAULT '',
  sort_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subject_detail_subject ON public.portal_subject_detail(subject_id);

-- Class-Subject Mapping
CREATE TABLE IF NOT EXISTS public.portal_class_subject (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  is_compulsory boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  UNIQUE (class_id, subject_id)
);

CREATE INDEX IF NOT EXISTS idx_class_subject_class ON public.portal_class_subject(class_id);
CREATE INDEX IF NOT EXISTS idx_class_subject_subject ON public.portal_class_subject(subject_id);

-- Curriculum (per class, per curriculum type)
CREATE TABLE IF NOT EXISTS public.portal_curriculum (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  curriculum_name varchar(50) NOT NULL DEFAULT 'CBSE',
  syllabus_description text DEFAULT '',
  learning_outcomes text DEFAULT '',
  semester_info text DEFAULT '',
  topics_covered text DEFAULT '',
  brochure_url text DEFAULT '',
  is_published boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (class_id, curriculum_name)
);

CREATE INDEX IF NOT EXISTS idx_curriculum_class ON public.portal_curriculum(class_id);

-- Faculty Profile (extends teacher profile with public info)
CREATE TABLE IF NOT EXISTS public.portal_faculty_profile (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES public.auth_user(id) ON DELETE CASCADE,
  designation varchar(150) DEFAULT '',
  qualification_detail text DEFAULT '',
  experience_years integer DEFAULT 0,
  specializations text DEFAULT '',
  achievements text DEFAULT '',
  research text DEFAULT '',
  bio text DEFAULT '',
  photo_url text DEFAULT '',
  is_published boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_faculty_user ON public.portal_faculty_profile(user_id);

-- Faculty-Subject-Class Mapping
CREATE TABLE IF NOT EXISTS public.portal_faculty_subject (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id integer NOT NULL REFERENCES public.portal_faculty_profile(id) ON DELETE CASCADE,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  UNIQUE (faculty_id, class_id, subject_id)
);

CREATE INDEX IF NOT EXISTS idx_faculty_subject_faculty ON public.portal_faculty_subject(faculty_id);

-- Academic Downloads (brochures, syllabus, prospectus, fee structure, calendar)
CREATE TABLE IF NOT EXISTS public.portal_academic_download (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(200) NOT NULL,
  description text DEFAULT '',
  file_url text NOT NULL,
  file_type varchar(30) DEFAULT 'PDF',
  category varchar(50) DEFAULT 'Curriculum',
  target_class_id integer REFERENCES public.portal_class(id) ON DELETE SET NULL,
  target_audience varchar(30) DEFAULT 'public',
  download_count integer DEFAULT 0,
  is_published boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_download_category ON public.portal_academic_download(category);
CREATE INDEX IF NOT EXISTS idx_download_class ON public.portal_academic_download(target_class_id);
