-- EduNova Portal Extension #6 — Timetable Management
-- Safe to run multiple times: every statement is IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.

-- ---------------------------------------------------------------------------
-- Core Timetable table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_timetable (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id        integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id      integer REFERENCES public.portal_subject(id) ON DELETE SET NULL,
  teacher_id      integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  day_of_week     varchar(10) NOT NULL CHECK (day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday')),
  period_number   smallint NOT NULL DEFAULT 1,
  start_time      time NOT NULL,
  end_time        time NOT NULL,
  room_number     varchar(50),
  meeting_link    text,
  is_break        boolean NOT NULL DEFAULT false,
  break_label     varchar(50) DEFAULT 'Break',
  academic_year   varchar(10) NOT NULL DEFAULT '2025-26',
  is_published    boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT portal_timetable_no_overlap
    UNIQUE (class_id, day_of_week, start_time, academic_year)
);

ALTER TABLE public.portal_timetable ADD COLUMN IF NOT EXISTS academic_year varchar(10) NOT NULL DEFAULT '2025-26';

-- Index for fast teacher schedule lookups
CREATE INDEX IF NOT EXISTS idx_portal_timetable_teacher
  ON public.portal_timetable(teacher_id, day_of_week);

-- Index for fast class schedule lookups
CREATE INDEX IF NOT EXISTS idx_portal_timetable_class
  ON public.portal_timetable(class_id, day_of_week, academic_year);

-- Index for room conflict detection
CREATE INDEX IF NOT EXISTS idx_portal_timetable_room
  ON public.portal_timetable(room_number, day_of_week, start_time)
  WHERE room_number IS NOT NULL;
