-- EduNova LMS Module Extension
-- Run AFTER portal_extension_auth_user.sql and portal_extension_facilities.sql
-- Adds: Live Classes, Recorded Classes, Enhanced Homework, Quiz Attempts,
--        Course Certificates, Course Announcements, LMS Settings, Learning Analytics

-- =============================================================================
-- 1. LIVE CLASSES
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.portal_live_class (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  title varchar(255) NOT NULL,
  description text DEFAULT '',
  subject_id integer REFERENCES public.portal_subject(id) ON DELETE SET NULL,
  class_id integer REFERENCES public.portal_class(id) ON DELETE SET NULL,
  meeting_platform varchar(30) NOT NULL DEFAULT 'Zoom'
    CHECK (meeting_platform IN ('Zoom','Google Meet','Microsoft Teams','Jitsi','Other')),
  meeting_link text NOT NULL DEFAULT '',
  meeting_password varchar(50) DEFAULT '',
  recording_url text DEFAULT '',
  scheduled_date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'Scheduled'
    CHECK (status IN ('Scheduled','Live','Completed','Cancelled')),
  attendance_recorded boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_live_class_attendance (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  live_class_id integer NOT NULL REFERENCES public.portal_live_class(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  joined_at timestamptz,
  left_at timestamptz,
  duration_minutes integer DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'Absent'
    CHECK (status IN ('Present','Absent','Late')),
  marked_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (live_class_id, student_id)
);

-- =============================================================================
-- 2. RECORDED CLASSES
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.portal_recorded_class (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  chapter_id integer REFERENCES public.portal_chapter(id) ON DELETE SET NULL,
  lesson_id integer REFERENCES public.portal_lesson(id) ON DELETE SET NULL,
  title varchar(255) NOT NULL,
  description text DEFAULT '',
  video_url text NOT NULL,
  video_platform varchar(20) NOT NULL DEFAULT 'Upload'
    CHECK (video_platform IN ('Upload','YouTube','Vimeo','Other')),
  thumbnail_url text DEFAULT '',
  duration_seconds integer DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'Published'
    CHECK (status IN ('Draft','Published','Archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_recorded_class_progress (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recorded_class_id integer NOT NULL REFERENCES public.portal_recorded_class(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  last_position_seconds integer NOT NULL DEFAULT 0,
  is_completed boolean NOT NULL DEFAULT false,
  watch_count integer NOT NULL DEFAULT 1,
  bookmarked boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (recorded_class_id, student_id)
);

-- =============================================================================
-- 3. ENHANCED HOMEWORK (separate from portal_homework for LMS integration)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.portal_lms_homework (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer REFERENCES public.portal_subject(id) ON DELETE SET NULL,
  title varchar(200) NOT NULL,
  description text NOT NULL DEFAULT '',
  instructions text DEFAULT '',
  attachments text DEFAULT '[]'::text,
  due_date timestamptz NOT NULL,
  max_marks integer DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'Published'
    CHECK (status IN ('Draft','Published','Closed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_lms_homework_submission (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id integer NOT NULL REFERENCES public.portal_lms_homework(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  submission_url text DEFAULT '',
  submission_text text DEFAULT '',
  marks_obtained numeric,
  teacher_feedback text DEFAULT '',
  grade varchar(10) DEFAULT '',
  status varchar(20) NOT NULL DEFAULT 'Submitted'
    CHECK (status IN ('Submitted','Reviewed','Returned')),
  submitted_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  UNIQUE (homework_id, student_id)
);

-- =============================================================================
-- 4. QUIZ ATTEMPTS (track individual attempts)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.portal_quiz_attempt (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id integer NOT NULL REFERENCES public.portal_quiz(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  score integer NOT NULL DEFAULT 0,
  total_questions integer NOT NULL DEFAULT 0,
  percentage numeric(5,2) NOT NULL DEFAULT 0,
  is_passed boolean NOT NULL DEFAULT false,
  time_taken_seconds integer DEFAULT 0,
  attempt_number integer NOT NULL DEFAULT 1,
  submitted_at timestamptz NOT NULL DEFAULT now()
);

-- =============================================================================
-- 5. QUESTION BANK ENHANCEMENTS
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.portal_lms_question (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  chapter varchar(200) DEFAULT '',
  question_type varchar(20) NOT NULL DEFAULT 'MCQ'
    CHECK (question_type IN ('MCQ','True_False','Fill_Blank','Match','Subjective','Coding')),
  difficulty varchar(20) NOT NULL DEFAULT 'Medium'
    CHECK (difficulty IN ('Easy','Medium','Hard')),
  question_text text NOT NULL,
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  correct_answer text NOT NULL DEFAULT '',
  explanation text DEFAULT '',
  bloom_taxonomy varchar(30) DEFAULT 'Remember',
  learning_outcome text DEFAULT '',
  marks integer DEFAULT 1,
  status varchar(20) NOT NULL DEFAULT 'Active'
    CHECK (status IN ('Active','Archived','Draft')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_lms_question_bank (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  description text DEFAULT '',
  question_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_lms_question_bank_item (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_id integer NOT NULL REFERENCES public.portal_lms_question_bank(id) ON DELETE CASCADE,
  question_id integer NOT NULL REFERENCES public.portal_lms_question(id) ON DELETE CASCADE,
  UNIQUE (bank_id, question_id)
);

-- =============================================================================
-- 6. COURSE CERTIFICATES
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.portal_course_certificate (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  certificate_id varchar(50) UNIQUE NOT NULL,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
  teacher_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  completion_date date NOT NULL DEFAULT CURRENT_DATE,
  completion_percent numeric(5,2) NOT NULL DEFAULT 0,
  qr_code_url text DEFAULT '',
  verification_url text DEFAULT '',
  file_url text DEFAULT '',
  teacher_signature_url text DEFAULT '',
  principal_signature_url text DEFAULT '',
  status varchar(20) NOT NULL DEFAULT 'Issued'
    CHECK (status IN ('Issued','Revoked','Expired')),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- =============================================================================
-- 7. COURSE ANNOUNCEMENTS
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.portal_course_announcement (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  title varchar(200) NOT NULL,
  message text NOT NULL,
  priority varchar(20) NOT NULL DEFAULT 'Normal'
    CHECK (priority IN ('Low','Normal','High','Urgent')),
  target_audience varchar(20) NOT NULL DEFAULT 'Students'
    CHECK (target_audience IN ('Students','All','Parents')),
  is_pinned boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- =============================================================================
-- 8. LMS SETTINGS
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.portal_lms_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key varchar(100) UNIQUE NOT NULL,
  setting_value text NOT NULL DEFAULT '',
  description text DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Seed default settings
INSERT INTO public.portal_lms_settings (setting_key, setting_value, description) VALUES
  ('course_categories', '["Mathematics","Science","English","Hindi","Social Science","Computer Science","Arts","Physical Education"]', 'Available course categories'),
  ('allowed_file_types', '["pdf","ppt","pptx","doc","docx","mp4","webm","mp3","png","jpeg","jpg","zip"]', 'Allowed file upload extensions'),
  ('max_upload_size_mb', '250', 'Maximum upload file size in MB'),
  ('storage_provider', 'Supabase', 'File storage provider'),
  ('course_visibility', 'Enrolled', 'Default course visibility: Enrolled, All, Class'),
  ('certificate_auto_generate', 'true', 'Auto-generate certificates on course completion'),
  ('live_class_platforms', '["Zoom","Google Meet","Microsoft Teams","Jitsi"]', 'Available video conferencing platforms'),
  ('quiz_max_attempts', '3', 'Maximum quiz attempts per student'),
  ('quiz_negative_marking', 'false', 'Enable negative marking in quizzes'),
  ('quiz_shuffle_options', 'true', 'Shuffle quiz options for each student')
ON CONFLICT (setting_key) DO NOTHING;

-- =============================================================================
-- 9. LEARNING ANALYTICS SNAPSHOTS
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.portal_learning_analytic (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
  total_lessons integer NOT NULL DEFAULT 0,
  completed_lessons integer NOT NULL DEFAULT 0,
  total_content_items integer NOT NULL DEFAULT 0,
  completed_content_items integer NOT NULL DEFAULT 0,
  total_live_classes integer NOT NULL DEFAULT 0,
  attended_live_classes integer NOT NULL DEFAULT 0,
  total_quizzes integer NOT NULL DEFAULT 0,
  quizzes_passed integer NOT NULL DEFAULT 0,
  average_quiz_score numeric(5,2) NOT NULL DEFAULT 0,
  total_assignments integer NOT NULL DEFAULT 0,
  assignments_submitted integer NOT NULL DEFAULT 0,
  total_homework integer NOT NULL DEFAULT 0,
  homework_submitted integer NOT NULL DEFAULT 0,
  total_learning_hours numeric(6,2) NOT NULL DEFAULT 0,
  overall_progress_percent numeric(5,2) NOT NULL DEFAULT 0,
  last_activity_at timestamptz,
  snapshot_date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, course_id, snapshot_date)
);

-- =============================================================================
-- INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_live_class_course ON public.portal_live_class(course_id);
CREATE INDEX IF NOT EXISTS idx_live_class_teacher ON public.portal_live_class(teacher_id);
CREATE INDEX IF NOT EXISTS idx_live_class_date ON public.portal_live_class(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_live_class_status ON public.portal_live_class(status);
CREATE INDEX IF NOT EXISTS idx_live_class_attendance_class ON public.portal_live_class_attendance(live_class_id);
CREATE INDEX IF NOT EXISTS idx_recorded_class_course ON public.portal_recorded_class(course_id);
CREATE INDEX IF NOT EXISTS idx_recorded_class_progress_student ON public.portal_recorded_class_progress(student_id);
CREATE INDEX IF NOT EXISTS idx_lms_homework_course ON public.portal_lms_homework(course_id);
CREATE INDEX IF NOT EXISTS idx_lms_homework_class ON public.portal_lms_homework(class_id);
CREATE INDEX IF NOT EXISTS idx_lms_homework_submission_student ON public.portal_lms_homework_submission(student_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempt_quiz ON public.portal_quiz_attempt(quiz_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempt_student ON public.portal_quiz_attempt(student_id);
CREATE INDEX IF NOT EXISTS idx_lms_question_subject ON public.portal_lms_question(subject_id);
CREATE INDEX IF NOT EXISTS idx_lms_question_teacher ON public.portal_lms_question(teacher_id);
CREATE INDEX IF NOT EXISTS idx_course_certificate_student ON public.portal_course_certificate(student_id);
CREATE INDEX IF NOT EXISTS idx_course_certificate_course ON public.portal_course_certificate(course_id);
CREATE INDEX IF NOT EXISTS idx_course_certificate_id ON public.portal_course_certificate(certificate_id);
CREATE INDEX IF NOT EXISTS idx_course_announcement_course ON public.portal_course_announcement(course_id);
CREATE INDEX IF NOT EXISTS idx_learning_analytic_student ON public.portal_learning_analytic(student_id);
CREATE INDEX IF NOT EXISTS idx_learning_analytic_course ON public.portal_learning_analytic(course_id);
CREATE INDEX IF NOT EXISTS idx_learning_analytic_date ON public.portal_learning_analytic(snapshot_date);
