# Generated by Django 5.0.6 on 2026-07-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_admissionenquiry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='allocated_class',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='allocated_section',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='counselling_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='counselling_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='counselling_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Converted', 'Converted')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='counsellor_id',
            field=models.IntegerField(blank=True, help_text='auth_user ID of assigned counsellor', null=True),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='curriculum',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('Cambridge', 'Cambridge'), ('IB', 'IB'), ('State_Board', 'State Board')], default='CBSE', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='eligibility_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='fee_transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='interview_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='interview_result',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='interview_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='is_waitlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='net_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='preferred_branch',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='scholarship_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='seat_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='source_of_enquiry',
            field=models.CharField(choices=[('Website', 'Website'), ('Walk-in', 'Walk-in'), ('Phone', 'Phone'), ('Email', 'Email'), ('Referral', 'Referral'), ('Social_Media', 'Social Media'), ('Advertisement', 'Advertisement')], default='Website', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='student_admission_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='student_roll_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='waitlist_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='status',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Registered', 'Registered'), ('Counselling_Pending', 'Counselling Pending'), ('Counselling_Done', 'Counselling Done'), ('Verification', 'Verification'), ('Eligibility_Check', 'Eligibility Check'), ('Screening', 'Screening'), ('Interview_Pending', 'Interview Pending'), ('Interview_Done', 'Interview Done'), ('Seat_Available', 'Seat Available'), ('Seat_Waitlisted', 'Seat Waitlisted'), ('Fee_Pending', 'Fee Pending'), ('Approved', 'Approved'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Enquiry', max_length=25),
        ),
        migrations.CreateModel(
            name='AdmissionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_user_id', models.IntegerField(blank=True, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('house', models.CharField(blank=True, default='', max_length=30)),
                ('class_teacher_id', models.IntegerField(blank=True, null=True)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, default='', max_length=20)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='admissions.admissionenquiry')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Birth_Certificate', 'Birth Certificate'), ('Aadhaar', 'Aadhaar'), ('Passport_Photo', 'Passport Photo'), ('Parent_ID', 'Parent ID'), ('Address_Proof', 'Address Proof'), ('Marks_Memo', 'Previous Marks Memo'), ('Transfer_Certificate', 'Transfer Certificate'), ('Medical_Certificate', 'Medical Certificate'), ('Caste_Certificate', 'Caste Certificate'), ('Income_Certificate', 'Income Certificate'), ('Other', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=200)),
                ('file_url', models.TextField()),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(default='', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.IntegerField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionenquiry')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(default='Admission_Fee', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scholarship_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_method', models.CharField(blank=True, default='', max_length=40)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('receipt_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_record', to='admissions.admissionenquiry')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_id', models.IntegerField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_type', models.CharField(default='Interview', max_length=30)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=30)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('recommendation', models.CharField(blank=True, choices=[('Recommended', 'Recommended'), ('Recommended_Conditions', 'Recommended with Conditions'), ('Not_Recommended', 'Not Recommended')], default='', max_length=30)),
                ('remarks', models.TextField(blank=True, default='')),
                ('parent_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='admissions.admissionenquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(max_length=30)),
                ('recipient_user_id', models.IntegerField(blank=True, null=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('push', 'Push')], default='in_app', max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='admissions.admissionenquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
