# Generated by Django 5.0.6 on 2026-07-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_admission_workflow_enhancement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionenquiry',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='admissionenquiry',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='admissionenquiry',
            name='parent_phone',
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='doc_aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='doc_address_proof',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='doc_birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='doc_parent_id',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='doc_passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='doc_previous_marks',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='doc_transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='father_company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='father_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='guardian_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='has_medical_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='medical_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='mother_company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='prev_school_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='prev_school_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
