# Generated by Django 5.0.6 on 2026-07-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_remove_admissionenquiry_parent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
